"""
categories.py
Defines the category → subcategory → operators grouping for the browse UI.
Each category maps to a display name, icon, and list of subcategories.
Each subcategory has a display name and list of operator IDs.
"""

# Structure:
# CATEGORIES = [
#     {
#         "id": "mesh",
#         "label": "Mesh",
#         "icon": "MESH_DATA",
#         "subcategories": [
#           {
#             "label": "Select",
#             "operators": ["mesh.select_all", ...]
#           }
#         ]
#       },
# ]


CATEGORIES = [
    {
        "id": "view2d",
        "label": "2D View",
        "icon": "OBJECT_HIDDEN",
        "subcategories": [
            {
                "label": "Navigation",
                "operators": [
                    "view2d.pan",
                    "view2d.scroll_up",
                    "view2d.scroll_down",
                    "view2d.scroll_left",
                    "view2d.scroll_right",
                    "view2d.zoom",
                    "view2d.zoom_in",
                    "view2d.zoom_out",
                    "view2d.zoom_border",
                    "view2d.smoothview",
                    "view2d.reset",
                ],
            },
            {
                "label": "Other",
                "operators": [],
            },
        ],
    },
    {
        "id": "view3d",
        "label": "3D View",
        "icon": "VIEW3D",
        "subcategories": [
            {
                "label": "Navigation",
                "operators": [
                    "view3d.view_orbit",
                    "view3d.view_roll",
                    "view3d.view_pan",
                    "view3d.zoom",
                    "view3d.dolly",
                    "view3d.view_center_cursor",
                    "view3d.view_center_pick",
                    "view3d.view_selected",
                    "view3d.view_all",
                    "view3d.view_camera",
                    "view3d.navigate",
                    "view3d.fly",
                    "view3d.walk",
                    "view3d.zoom_border",
                    "view3d.zoom_camera_1_to_1",
                    "view3d.view_axis",
                    "view3d.view_persportho",
                    "view3d.localview",
                    "view3d.localview_remove_from",
                    "view3d.object_mode_pie_or_toggle",
                    "view3d.ndof_orbit",
                    "view3d.ndof_orbit_zoom",
                    "view3d.ndof_pan",
                    "view3d.ndof_all",
                    "view3d.smoothview",
                ],
            },
            {
                "label": "Viewport Display",
                "operators": [
                    "view3d.toggle_shading",
                    "view3d.wireframe_toggle",
                    "view3d.xray_toggle",
                    "view3d.overlay_toggle",
                    "view3d.toggle_matcap_flip",
                    "view3d.view_lock_to_active",
                    "view3d.view_lock_clear",
                    "view3d.clip_border",
                    "view3d.render_border",
                    "view3d.clear_render_border",
                ],
            },
            {
                "label": "Cursor",
                "operators": [
                    "view3d.cursor3d",
                    "view3d.snap_cursor_to_selected",
                    "view3d.snap_cursor_to_center",
                    "view3d.snap_cursor_to_active",
                    "view3d.snap_cursor_to_grid",
                    "view3d.snap_selected_to_cursor",
                    "view3d.snap_selected_to_grid",
                ],
            },
            {
                "label": "Selection",
                "operators": [
                    "view3d.select",
                    "view3d.select_box",
                    "view3d.select_circle",
                    "view3d.select_lasso",
                    "view3d.select_menu",
                ],
            },
            {
                "label": "Gizmo & Transform",
                "operators": [
                    "view3d.move",
                    "view3d.rotate",
                    "view3d.scale",
                ],
            },
        ],
    },
    {
        "id": "animation",
        "label": "Animation",
        "icon": "ANIM_DATA",
        "subcategories": [
            {
                "label": "Keyframes",
                "operators": [
                    "anim.keyframe_insert",
                    "anim.keyframe_insert_menu",
                    "anim.keyframe_delete",
                    "anim.keyframe_insert_button",
                    "anim.keyframe_delete_button",
                    "anim.keyframe_clear_button",
                    "anim.keyframe_delete_vse",
                    "anim.keying_set_active_set",
                    "anim.keyingset_button_add",
                    "anim.keyingset_button_remove",
                ],
            },
            {
                "label": "Frame",
                "operators": [
                    "anim.change_frame",
                    "anim.start_frame_set",
                    "anim.end_frame_set",
                    "anim.previewrange_set",
                    "anim.previewrange_clear",
                    "screen.animation_play",
                    "screen.animation_cancel",
                    "screen.frame_jump",
                    "screen.frame_offset",
                    "screen.keyframe_jump",
                ],
            },
            {
                "label": "Channels",
                "operators": [
                    "anim.channels_click",
                    "anim.channels_select_all",
                    "anim.channels_select_box",
                    "anim.channels_select_filter",
                    "anim.channels_collapse",
                    "anim.channels_expand",
                    "anim.channels_move",
                    "anim.channels_group",
                    "anim.channels_ungroup",
                    "anim.channels_delete",
                    "anim.channels_rename",
                    "anim.channels_editable_toggle",
                    "anim.channels_setting_toggle",
                    "anim.channels_setting_enable",
                    "anim.channels_setting_disable",
                    "anim.channels_view_selected",
                ],
            },
            {
                "label": "Drivers",
                "operators": [
                    "anim.driver_button_add",
                    "anim.driver_button_remove",
                ],
            },
            {
                "label": "Action Editor",
                "operators": [
                    "action.select_all",
                    "action.select_box",
                    "action.select_circle",
                    "action.select_lasso",
                    "action.select_column",
                    "action.select_linked",
                    "action.select_more",
                    "action.select_less",
                    "action.select_leftright",
                    "action.keyframe_insert",
                    "action.duplicate_move",
                    "action.delete",
                    "action.copy",
                    "action.paste",
                    "action.mirror",
                    "action.snap",
                    "action.handle_type",
                    "action.interpolation_type",
                    "action.easing_type",
                    "action.extrapolation_type",
                    "action.keyframe_type",
                    "action.bake_keys",
                    "action.frame_jump",
                    "action.view_all",
                    "action.view_selected",
                    "action.view_frame",
                    "action.previewrange_set",
                ],
            },
            {
                "label": "NLA",
                "operators": [
                    "nla.select_all",
                    "nla.select_box",
                    "nla.select_leftright",
                    "nla.duplicate_move",
                    "nla.duplicate_linked_move",
                    "nla.delete",
                    "nla.split",
                    "nla.meta_add",
                    "nla.meta_remove",
                    "nla.mute_toggle",
                    "nla.swap",
                    "nla.move_up",
                    "nla.move_down",
                    "nla.snap",
                    "nla.apply_scale",
                    "nla.clear_scale",
                    "nla.actionclip_add",
                    "nla.soundclip_add",
                    "nla.transition_add",
                    "nla.tracks_add",
                    "nla.tracks_delete",
                    "nla.tweakmode_enter",
                    "nla.tweakmode_exit",
                    "nla.make_single_user",
                    "nla.view_all",
                    "nla.view_selected",
                    "nla.view_frame",
                    "nla.duplicate",
                ],
            },
            {
                "label": "Graph Editor",
                "operators": [
                    "graph.select_all",
                    "graph.select_box",
                    "graph.select_circle",
                    "graph.select_lasso",
                    "graph.select_column",
                    "graph.select_linked",
                    "graph.select_more",
                    "graph.select_less",
                    "graph.select_leftright",
                    "graph.keyframe_insert",
                    "graph.duplicate_move",
                    "graph.delete",
                    "graph.copy",
                    "graph.paste",
                    "graph.mirror",
                    "graph.snap",
                    "graph.handle_type",
                    "graph.interpolation_type",
                    "graph.easing_type",
                    "graph.extrapolation_type",
                    "graph.keyframe_type",
                    "graph.bake_keys",
                    "graph.frame_jump",
                    "graph.view_all",
                    "graph.view_selected",
                    "graph.view_frame",
                    "graph.previewrange_set",
                    "graph.hide",
                    "graph.reveal",
                    "graph.fmodifier_add",
                    "graph.fmodifier_copy",
                    "graph.fmodifier_paste",
                    "graph.driver_delete_invalid",
                    "graph.decimate",
                    "graph.unbake",
                    "graph.keys_to_samples",
                    "graph.samples_to_keys",
                    "graph.sound_to_samples",
                    "graph.euler_filter",
                    "graph.clean",
                    "graph.smooth",
                    "graph.previous_keyframe",
                    "graph.next_keyframe",
                ],
            },
        ],
    },
    {
        "id": "armature",
        "label": "Armature",
        "icon": "ARMATURE_DATA",
        "subcategories": [
            {
                "label": "Edit",
                "operators": [
                    "armature.bone_primitive_add",
                    "armature.duplicate_move",
                    "armature.extrude_move",
                    "armature.extrude_forked",
                    "armature.click_extrude",
                    "armature.fill",
                    "armature.split",
                    "armature.separate",
                    "armature.dissolve",
                    "armature.delete",
                    "armature.switch_direction",
                ],
            },
            {
                "label": "Select",
                "operators": [
                    "armature.select_all",
                    "armature.select_more",
                    "armature.select_less",
                    "armature.select_linked",
                    "armature.select_linked_pick",
                    "armature.select_similar",
                    "armature.select_hierarchy",
                    "armature.select_mirror",
                    "armature.shortest_path_pick",
                ],
            },
            {
                "label": "Parent / Roll",
                "operators": [
                    "armature.parent_set",
                    "armature.parent_clear",
                    "armature.calculate_roll",
                    "armature.roll_clear",
                    "armature.align",
                ],
            },
            {
                "label": "Collections",
                "operators": [
                    "armature.assign_to_collection",
                    "armature.move_to_collection",
                ],
            },
            {
                "label": "Hide / Reveal",
                "operators": [
                    "armature.hide",
                    "armature.reveal",
                ],
            },
        ],
    },
    {
        "id": "curve",
        "label": "Curve",
        "icon": "CURVE_DATA",
        "subcategories": [
            {
                "label": "Edit",
                "operators": [
                    "curve.duplicate_move",
                    "curve.extrude_move",
                    "curve.make_segment",
                    "curve.split",
                    "curve.separate",
                    "curve.dissolve_verts",
                    "curve.vertex_add",
                    "curve.pen",
                    "curve.draw",
                ],
            },
            {
                "label": "Select",
                "operators": [
                    "curve.select_all",
                    "curve.select_more",
                    "curve.select_less",
                    "curve.select_linked",
                    "curve.select_linked_pick",
                    "curve.select_similar",
                    "curve.select_row",
                    "curve.shortest_path_pick",
                ],
            },
            {
                "label": "Handle / Normals",
                "operators": [
                    "curve.handle_type_set",
                    "curve.cyclic_toggle",
                    "curve.normals_make_consistent",
                    "curve.tilt_clear",
                ],
            },
            {
                "label": "Hide / Reveal",
                "operators": [
                    "curve.hide",
                    "curve.reveal",
                ],
            },
        ],
    },
    {
        "id": "curves",
        "label": "Curves (Hair)",
        "icon": "CURVES_DATA",
        "subcategories": [
            {
                "label": "Edit",
                "operators": [
                    "curves.duplicate_move",
                    "curves.delete",
                    "curves.extrude_move",
                    "curves.split",
                    "curves.separate",
                    "curves.cyclic_toggle",
                    "curves.tilt_clear",
                    "curves.handle_type_set",
                    "curves.draw",
                    "curves.pen",
                ],
            },
            {
                "label": "Select",
                "operators": [
                    "curves.select_all",
                    "curves.select_more",
                    "curves.select_less",
                    "curves.select_linked",
                    "curves.select_linked_pick",
                    "curves.set_selection_domain",
                ],
            },
            {
                "label": "Sculpt",
                "operators": [
                    "sculpt_curves.brush_stroke",
                    "sculpt_curves.select_grow",
                    "sculpt_curves.min_distance_edit",
                ],
            },
        ],
    },
    {
        "id": "grease_pencil",
        "label": "Grease Pencil",
        "icon": "GREASEPENCIL",
        "subcategories": [
            {
                "label": "Edit",
                "operators": [
                    "grease_pencil.select_all",
                    "grease_pencil.select_box",
                    "grease_pencil.select_circle",
                    "grease_pencil.select_lasso",
                    "grease_pencil.select_more",
                    "grease_pencil.select_less",
                    "grease_pencil.select_linked",
                    "grease_pencil.select_linked_pick",
                    "grease_pencil.duplicate_move",
                    "grease_pencil.delete",
                    "grease_pencil.dissolve",
                    "grease_pencil.extrude_move",
                    "grease_pencil.cyclical_set",
                    "grease_pencil.separate",
                    "grease_pencil.split",
                ],
            },
            {
                "label": "Draw",
                "operators": [
                    "grease_pencil.brush_stroke",
                    "grease_pencil.sculpt_paint",
                    "grease_pencil.weight_brush_stroke",
                    "grease_pencil.vertex_paint",
                    "grease_pencil.fill",
                    "grease_pencil.interpolate",
                    "grease_pencil.interpolate_sequence",
                ],
            },
            {
                "label": "Annotation",
                "operators": [
                    "gpencil.annotate",
                    "gpencil.annotation_add",
                    "gpencil.annotation_active_frame_delete",
                ],
            },
        ],
    },
    {
        "id": "image",
        "label": "Image Editor",
        "icon": "IMAGE_DATA",
        "subcategories": [
            {
                "label": "View",
                "operators": [
                    "image.view_all",
                    "image.view_selected",
                    "image.view_center_cursor",
                    "image.view_zoom_in",
                    "image.view_zoom_out",
                    "image.view_zoom_ratio",
                    "image.view_ndof",
                    "image.view_pan",
                ],
            },
            {
                "label": "Edit",
                "operators": [
                    "image.flip",
                    "image.rotate_orthogonal",
                    "image.invert",
                    "image.resize",
                    "image.crop",
                ],
            },
            {
                "label": "File",
                "operators": [
                    "image.new",
                    "image.open",
                    "image.reload",
                    "image.save",
                    "image.save_as",
                    "image.pack",
                ],
            },
        ],
    },
    {
        "id": "mesh",
        "label": "Mesh",
        "icon": "MESH_DATA",
        "subcategories": [
            {
                "label": "Select",
                "operators": [
                    "mesh.select_all",
                    "mesh.select_more",
                    "mesh.select_less",
                    "mesh.select_linked",
                    "mesh.select_linked_pick",
                    "mesh.select_similar",
                    "mesh.select_mode",
                    "mesh.select_loop_adjacent_region",
                    "mesh.select_mirror",
                    "mesh.select_non_manifold",
                    "mesh.select_next_item",
                    "mesh.select_prev_item",
                    "mesh.shortest_path_pick",
                ],
            },
            {
                "label": "Add / Create",
                "operators": [
                    "mesh.primitive_plane_add",
                    "mesh.primitive_cube_add",
                    "mesh.primitive_circle_add",
                    "mesh.primitive_uv_sphere_add",
                    "mesh.primitive_ico_sphere_add",
                    "mesh.primitive_cylinder_add",
                    "mesh.primitive_cone_add",
                    "mesh.primitive_torus_add",
                    "mesh.primitive_grid_add",
                    "mesh.primitive_monkey_add",
                ],
            },
            {
                "label": "Edit",
                "operators": [
                    "mesh.duplicate_move",
                    "mesh.extrude_region_move",
                    "mesh.extrude_faces_move",
                    "mesh.extrude_edges_move",
                    "mesh.extrude_vertices_move",
                    "mesh.inset",
                    "mesh.bevel",
                    "mesh.loopcut",
                    "mesh.offset_edge_loops_slide",
                    "mesh.spin",
                    "mesh.knife_tool",
                    "mesh.bisect",
                    "mesh.fill",
                    "mesh.fill_grid",
                    "mesh.bridge_edge_loops",
                    "mesh.separate",
                    "mesh.split",
                    "mesh.merge",
                    "mesh.vertices_smooth",
                    "mesh.edge_face_add",
                    "mesh.flip_normals",
                    "mesh.normals_make_consistent",
                    "mesh.dissolve_contextual_bfa",
                    "mesh.mark_seam",
                    "mesh.mark_sharp",
                    "mesh.vert_connect_path",
                    "mesh.tris_convert_to_quads",
                ],
            },
            {
                "label": "Hide / Reveal",
                "operators": [
                    "mesh.hide",
                    "mesh.reveal",
                ],
            },
            {
                "label": "Delete",
                "operators": [
                    "mesh.delete",
                    "mesh.dissolve_verts",
                    "mesh.dissolve_edges",
                    "mesh.dissolve_faces",
                    "mesh.edge_collapse",
                    "mesh.delete_edgeloop",
                ],
            },
        ],
    },
    {
        "id": "node_editor",
        "label": "Node Editor",
        "icon": "NODETREE",
        "subcategories": [
            {
                "label": "Nodes",
                "operators": [
                    "node.duplicate_move",
                    "node.duplicate_move_keep_inputs",
                    "node.duplicate_move_linked",
                    "node.delete",
                    "node.delete_reconnect",
                    "node.delete_copy_reconnect",
                    "node.mute_toggle",
                    "node.hide_toggle",
                    "node.preview_toggle",
                    "node.hide_socket_toggle",
                    "node.translate_attach",
                    "node.move_detach_links",
                    "node.resize",
                    "node.find_node",
                ],
            },
            {
                "label": "Select",
                "operators": [
                    "node.select",
                    "node.select_all",
                    "node.select_box",
                    "node.select_circle",
                    "node.select_lasso",
                    "node.select_linked_from",
                    "node.select_linked_to",
                    "node.select_grouped",
                    "node.select_same_type_step",
                    "node.select_link_viewer",
                ],
            },
            {
                "label": "Links",
                "operators": [
                    "node.link",
                    "node.link_make",
                    "node.links_cut",
                    "node.links_mute",
                    "node.detach",
                    "node.move_detach_links_release",
                    "node.add_reroute",
                    "node.parent_set",
                ],
            },
            {
                "label": "Groups",
                "operators": [
                    "node.group_make",
                    "node.group_ungroup",
                    "node.group_separate",
                    "node.group_edit",
                    "node.group_enter_exit",
                    "node.join",
                    "node.join_named",
                    "node.join_nodes",
                ],
            },
            {
                "label": "View",
                "operators": [
                    "node.view_all",
                    "node.view_selected",
                    "node.backimage_fit",
                    "node.backimage_move",
                    "node.backimage_zoom",
                    "node.backimage_sample",
                    "node.viewer_border",
                    "node.clear_viewer_border",
                    "node.read_viewlayers",
                    "node.render_changed",
                    "node.connect_to_output",
                    "node.viewer_shortcut_get",
                    "node.viewer_shortcut_set",
                ],
            },
            {
                "label": "Clipboard",
                "operators": [
                    "node.clipboard_copy",
                    "node.clipboard_paste",
                ],
            },
        ],
    },
    {
        "id": "object",
        "label": "Object",
        "icon": "OBJECT_DATA",
        "subcategories": [
            {
                "label": "Duplicate",
                "operators": [
                    "object.duplicate_move",
                    "object.duplicate_move_linked",
                    "object.duplicates_make_real",
                    "object.duplicate",
                ],
            },
            {
                "label": "Transform",
                "operators": [
                    "transform.translate",
                    "transform.rotate",
                    "transform.resize",
                    "transform.mirror",
                    "transform.bend",
                    "transform.push_pull",
                    "transform.shear",
                    "transform.tosphere",
                    "object.location_clear",
                    "object.rotation_clear",
                    "object.scale_clear",
                    "object.origin_set",
                    "object.origin_clear",
                ],
            },
            {
                "label": "Select",
                "operators": [
                    "object.select_all",
                    "object.select_grouped",
                    "object.select_hierarchy",
                    "object.select_less",
                    "object.select_linked",
                    "object.select_mirror",
                    "object.select_more",
                ],
            },
            {
                "label": "Parent",
                "operators": [
                    "object.parent_set",
                    "object.parent_clear",
                    "object.parent_no_inverse_set",
                    "object.vertex_parent_set",
                ],
            },
            {
                "label": "Collections",
                "operators": [
                    "object.move_to_collection",
                    "object.link_to_collection",
                    "object.hide_collection",
                    "object.hide_view_set",
                    "object.hide_view_clear",
                    "collection.create",
                    "collection.objects_add_active",
                    "collection.objects_remove",
                    "collection.objects_remove_active",
                    "collection.objects_remove_all",
                ],
            },
            {
                "label": "Modifiers",
                "operators": [
                    "object.modifier_apply",
                    "object.modifier_copy",
                    "object.modifier_remove",
                    "object.modifier_set_active",
                    "object.add_modifier_menu",
                    "object.subdivision_set",
                    "object.voxel_remesh",
                    "object.voxel_size_edit",
                ],
            },
            {
                "label": "Relations",
                "operators": [
                    "object.join",
                    "object.convert",
                    "object.make_local",
                    "object.track_set",
                    "object.track_clear",
                    "object.transfer_mode",
                    "object.data_transfer",
                ],
            },
            {
                "label": "Constraints",
                "operators": [
                    "object.constraint_add_with_targets",
                    "object.constraints_clear",
                    "constraint.apply",
                    "constraint.copy",
                    "constraint.delete",
                ],
            },
        ],
    },
    {
        "id": "outliner",
        "label": "Outliner",
        "icon": "OUTLINER",
        "subcategories": [
            {
                "label": "Select",
                "operators": [
                    "outliner.item_activate",
                    "outliner.select_all",
                    "outliner.select_box",
                    "outliner.select_walk",
                    "outliner.show_active",
                    "outliner.collection_objects_select",
                ],
            },
            {
                "label": "Edit",
                "operators": [
                    "outliner.item_rename",
                    "outliner.delete",
                    "outliner.collection_new",
                    "outliner.id_copy",
                    "outliner.id_paste",
                    "outliner.id_operation",
                    "outliner.operation",
                ],
            },
            {
                "label": "View",
                "operators": [
                    "outliner.show_hierarchy",
                    "outliner.show_one_level",
                    "outliner.expanded_toggle",
                    "outliner.unhide_all",
                    "outliner.hide",
                    "outliner.item_openclose",
                    "outliner.scroll_page",
                ],
            },
            {
                "label": "Filter",
                "operators": [
                    "outliner.start_filter",
                    "outliner.clear_filter",
                ],
            },
        ],
    },
    {
        "id": "paint",
        "label": "Paint",
        "icon": "BRUSH_DATA",
        "subcategories": [
            {
                "label": "Paint",
                "operators": [
                    "paint.image_paint",
                    "paint.vertex_paint",
                    "paint.weight_paint",
                    "paint.brush_colors_flip",
                    "paint.sample_color",
                    "paint.grab_clone",
                    "paint.vertex_color_set",
                    "paint.weight_set",
                    "paint.weight_gradient",
                    "paint.weight_sample",
                    "paint.weight_sample_group",
                ],
            },
            {
                "label": "Face Select",
                "operators": [
                    "paint.face_select_all",
                    "paint.face_select_linked",
                    "paint.face_select_linked_pick",
                    "paint.face_select_loop",
                    "paint.face_select_more",
                    "paint.face_select_less",
                    "paint.face_select_hide",
                    "paint.face_vert_reveal",
                ],
            },
            {
                "label": "Vertex Select",
                "operators": [
                    "paint.vert_select_all",
                    "paint.vert_select_linked",
                    "paint.vert_select_linked_pick",
                    "paint.vert_select_loop",
                    "paint.vert_select_more",
                    "paint.vert_select_less",
                    "paint.vert_select_hide",
                ],
            },
            {
                "label": "Mask",
                "operators": [
                    "paint.mask_flood_fill",
                    "paint.mask_box_gesture",
                    "paint.mask_lasso_gesture",
                    "paint.mask_line_gesture",
                    "paint.mask_polyline_gesture",
                ],
            },
            {
                "label": "Hide / Show",
                "operators": [
                    "paint.hide_show",
                    "paint.hide_show_all",
                    "paint.hide_show_lasso_gesture",
                    "paint.hide_show_line_gesture",
                    "paint.hide_show_polyline_gesture",
                    "paint.visibility_filter",
                ],
            },
        ],
    },
    {
        "id": "particle",
        "label": "Particle",
        "icon": "PARTICLES",
        "subcategories": [
            {
                "label": "Edit",
                "operators": [
                    "particle.brush_edit",
                    "particle.delete",
                    "particle.weight_set",
                ],
            },
            {
                "label": "Select",
                "operators": [
                    "particle.select_all",
                    "particle.select_more",
                    "particle.select_less",
                    "particle.select_linked",
                    "particle.select_linked_pick",
                ],
            },
            {
                "label": "Hide / Reveal",
                "operators": [
                    "particle.hide",
                    "particle.reveal",
                ],
            },
        ],
    },
    {
        "id": "pose",
        "label": "Pose",
        "icon": "POSE_HLT",
        "subcategories": [
            {
                "label": "Pose",
                "operators": [
                    "poselib.apply_pose_asset",
                    "poselib.blend_pose_asset",
                    "pose.copy",
                    "pose.paste",
                    "pose.push",
                    "pose.relax",
                    "pose.breakdown",
                    "pose.blend_to_neighbor",
                    "pose.quaternions_flip",
                ],
            },
            {
                "label": "Select",
                "operators": [
                    "pose.select_all",
                    "pose.select_grouped",
                    "pose.select_hierarchy",
                    "pose.select_linked",
                    "pose.select_linked_pick",
                    "pose.select_mirror",
                    "pose.select_parent",
                ],
            },
            {
                "label": "Transform Clear",
                "operators": [
                    "pose.loc_clear",
                    "pose.rot_clear",
                    "pose.scale_clear",
                ],
            },
            {
                "label": "IK / Constraints",
                "operators": [
                    "pose.ik_add",
                    "pose.ik_clear",
                    "pose.constraint_add_with_targets",
                    "pose.constraints_clear",
                    "pose.rotation_mode_set",
                ],
            },
            {
                "label": "Hide / Reveal",
                "operators": [
                    "pose.hide",
                    "pose.reveal",
                ],
            },
        ],
    },
    {
        "id": "render",
        "label": "Render",
        "icon": "RENDER_STILL",
        "subcategories": [
            {
                "label": "Render",
                "operators": [
                    "render.render",
                    "render.play_rendered_anim",
                    "render.view_show",
                    "render.view_cancel",
                ],
            },
        ],
    },
    {
        "id": "screen",
        "label": "Screen / Window",
        "icon": "SCREEN_BACK",
        "subcategories": [
            {
                "label": "Areas",
                "operators": [
                    "screen.area_split",
                    "screen.area_join",
                    "screen.area_move",
                    "screen.area_dupli",
                    "screen.area_swap",
                    "screen.area_options",
                    "screen.screen_full_area",
                    "screen.region_quadview",
                    "screen.region_flip",
                    "screen.region_context_menu",
                ],
            },
            {
                "label": "Undo / Redo",
                "operators": [
                    "ed.undo",
                    "ed.redo",
                    "ed.undo_history",
                    "screen.redo_last",
                    "screen.repeat_last",
                    "screen.repeat_history",
                ],
            },
            {
                "label": "File",
                "operators": [
                    "wm.save_mainfile",
                    "wm.save_as_mainfile",
                    "wm.open_mainfile",
                    "wm.append",
                    "wm.link",
                    "wm.save_homefile",
                    "wm.read_homefile",
                    "wm.quit_blender",
                ],
            },
            {
                "label": "Search / Tools",
                "operators": [
                    "wm.search_menu",
                    "wm.toolbar",
                    "wm.toolbar_fallback_pie",
                    "wm.call_menu",
                    "wm.call_menu_pie",
                    "wm.call_panel",
                    "wm.batch_rename",
                    "wm.console_toggle",
                    "wm.window_fullscreen_toggle",
                    "wm.window_new",
                    "wm.debug_menu",
                    "screen.screenshot",
                    "script.reload",
                ],
            },
            {
                "label": "Workspace",
                "operators": [
                    "screen.workspace_cycle",
                    "screen.screen_set",
                    "screen.space_context_cycle",
                    "screen.space_type_set_or_cycle",
                    "screen.userpref_show",
                ],
            },
            {
                "label": "Context Operators",
                "operators": [
                    "wm.context_toggle",
                    "wm.context_toggle_enum",
                    "wm.context_set_boolean",
                    "wm.context_set_enum",
                    "wm.context_set_float",
                    "wm.context_set_int",
                    "wm.context_set_string",
                    "wm.context_set_value",
                    "wm.context_set_id",
                    "wm.context_scale_float",
                    "wm.context_scale_int",
                    "wm.context_cycle_enum",
                    "wm.context_cycle_int",
                    "wm.context_cycle_array",
                    "wm.context_menu_enum",
                    "wm.context_pie_enum",
                    "wm.context_modal_mouse",
                    "wm.context_collection_boolean_set",
                ],
            },
        ],
    },
    {
        "id": "sculpt",
        "label": "Sculpt",
        "icon": "SCULPTMODE_HLT",
        "subcategories": [
            {
                "label": "Brush",
                "operators": [
                    "sculpt.brush_stroke",
                    "sculpt.detail_flood_fill",
                    "sculpt.dyntopo_detail_size_edit",
                    "sculpt.set_pivot_position",
                    "sculpt.expand",
                ],
            },
            {
                "label": "Filters",
                "operators": [
                    "sculpt.mesh_filter",
                    "sculpt.cloth_filter",
                    "sculpt.color_filter",
                    "sculpt.mask_by_color",
                ],
            },
            {
                "label": "Face Sets",
                "operators": [
                    "sculpt.face_set_edit",
                    "sculpt.face_set_change_visibility",
                    "sculpt.face_set_box_gesture",
                    "sculpt.face_set_lasso_gesture",
                    "sculpt.face_set_line_gesture",
                    "sculpt.face_set_polyline_gesture",
                ],
            },
            {
                "label": "Trim",
                "operators": [
                    "sculpt.trim_box_gesture",
                    "sculpt.trim_lasso_gesture",
                    "sculpt.trim_line_gesture",
                    "sculpt.trim_polyline_gesture",
                    "sculpt.project_line_gesture",
                ],
            },
            {
                "label": "UV Sculpt",
                "operators": [
                    "sculpt.uv_sculpt_grab",
                    "sculpt.uv_sculpt_pinch",
                    "sculpt.uv_sculpt_relax",
                ],
            },
        ],
    },
    {
        "id": "font",
        "label": "Text Object",
        "icon": "FONT_DATA",
        "subcategories": [
            {
                "label": "Edit",
                "operators": [
                    "font.text_insert",
                    "font.delete",
                    "font.line_break",
                    "font.move",
                    "font.move_select",
                    "font.select_all",
                    "font.select_word",
                    "font.selection_set",
                    "font.style_toggle",
                    "font.change_character",
                    "font.change_spacing",
                    "font.text_copy",
                    "font.text_cut",
                    "font.text_paste",
                ],
            },
        ],
    },
    {
        "id": "transform",
        "label": "Transform",
        "icon": "ORIENTATION_GLOBAL",
        "subcategories": [
            {
                "label": "Basic",
                "operators": [
                    "transform.translate",
                    "transform.rotate",
                    "transform.resize",
                    "transform.mirror",
                    "transform.bend",
                    "transform.shear",
                    "transform.tosphere",
                    "transform.push_pull",
                    "transform.shrink_fatten",
                    "transform.tilt",
                    "transform.vertex_random",
                ],
            },
            {
                "label": "Advanced",
                "operators": [
                    "transform.edge_slide",
                    "transform.vert_slide",
                    "transform.edge_crease",
                    "transform.bbone_resize",
                    "transform.skin_resize",
                    "transform.seq_slide",
                    "transform.transform",
                    "transform.from_gizmo",
                    "transform.create_orientation",
                ],
            },
            {
                "label": "Proportional / Snap",
                "operators": [
                    "tool_settings.use_proportional_edit",
                    "tool_settings.use_proportional_connected",
                    "tool_settings.proportional_edit_falloff",
                    "tool_settings.use_snap",
                    "tool_settings.transform_pivot_point",
                ],
            },
        ],
    },
    {
        "id": "uv",
        "label": "UV Editor",
        "icon": "UV",
        "subcategories": [
            {
                "label": "Select",
                "operators": [
                    "uv.select",
                    "uv.select_all",
                    "uv.select_box",
                    "uv.select_circle",
                    "uv.select_lasso",
                    "uv.select_loop",
                    "uv.select_edge_ring",
                    "uv.select_linked",
                    "uv.select_linked_pick",
                    "uv.select_more",
                    "uv.select_less",
                    "uv.select_similar",
                    "uv.select_pinned",
                    "uv.select_split",
                    "uv.select_mode",
                    "uv.shortest_path_pick",
                ],
            },
            {
                "label": "Edit",
                "operators": [
                    "uv.unwrap",
                    "uv.pack_islands",
                    "uv.average_islands_scale",
                    "uv.minimize_stretch",
                    "uv.stitch",
                    "uv.pin",
                    "uv.rip_move",
                    "uv.mark_seam",
                    "uv.clear_seam",
                    "uv.move_on_axis",
                    "uv.custom_region_set",
                ],
            },
            {
                "label": "Hide / Reveal",
                "operators": [
                    "uv.hide",
                    "uv.reveal",
                ],
            },
            {
                "label": "Clipboard",
                "operators": [
                    "uv.copy",
                    "uv.paste",
                    "uv.cursor_set",
                ],
            },
        ],
    },
    {
        "id": "sequencer",
        "label": "Video Sequencer",
        "icon": "SEQUENCE",
        "subcategories": [
            {
                "label": "Select",
                "operators": [
                    "sequencer.select",
                    "sequencer.select_all",
                    "sequencer.select_box",
                    "sequencer.select_circle",
                    "sequencer.select_lasso",
                    "sequencer.select_more",
                    "sequencer.select_less",
                    "sequencer.select_linked",
                    "sequencer.select_linked_pick",
                    "sequencer.select_handle",
                    "sequencer.select_side_of_frame",
                    "sequencer.select_grouped",
                ],
            },
            {
                "label": "Edit",
                "operators": [
                    "sequencer.duplicate_move",
                    "sequencer.duplicate_move_linked",
                    "sequencer.delete",
                    "sequencer.split",
                    "sequencer.slip",
                    "sequencer.snap",
                    "sequencer.swap",
                    "sequencer.swap_inputs",
                    "sequencer.offset_clear",
                    "sequencer.gap_insert",
                    "sequencer.gap_remove",
                    "sequencer.images_separate",
                    "sequencer.reassign_inputs",
                    "sequencer.connect",
                    "sequencer.strip_transform_clear",
                ],
            },
            {
                "label": "Meta",
                "operators": [
                    "sequencer.meta_make",
                    "sequencer.meta_separate",
                    "sequencer.meta_toggle",
                ],
            },
            {
                "label": "Lock / Mute",
                "operators": [
                    "sequencer.lock",
                    "sequencer.unlock",
                    "sequencer.mute",
                    "sequencer.unmute",
                ],
            },
            {
                "label": "View",
                "operators": [
                    "sequencer.view_all",
                    "sequencer.view_all_preview",
                    "sequencer.view_selected",
                    "sequencer.view_frame",
                    "sequencer.view_zoom_ratio",
                    "sequencer.view_ghost_border",
                    "sequencer.strip_jump",
                ],
            },
            {
                "label": "Clipboard",
                "operators": [
                    "sequencer.copy",
                    "sequencer.paste",
                ],
            },
        ],
    },
]


def get_category_by_id(cat_id):
    for c in CATEGORIES:
        if c["id"] == cat_id:
            return c
    return None
