"""
Maps raw Blender/Bforartists operator IDs to human-friendly display names.
Used in Friendly Mode of the operator search/browse popup.

Format:
  FRIENDLY_NAMES = {
      "operator.id": ("Friendly Name", "blender" | "bforartists"),
  }

"blender"      = available in standard Blender
"bforartists"  = exclusive to Bforartists (hidden when running standard Blender)
"""

import bpy

FRIENDLY_NAMES = {
    # ---- Object ----
    "object.duplicate_move":          ("Add Duplicate", "blender"),
    "object.duplicate_move_linked":   ("Duplicate Linked", "blender"),
    "object.duplicates_make_real":    ("Make Duplicates Real", "blender"),
    "object.duplicate":               ("Duplicate Objects", "blender"),
    "object.delete":                  ("Delete Object", "blender"),
    "object.join":                    ("Join Objects", "blender"),
    "object.convert":                 ("Convert To", "blender"),
    "object.make_local":              ("Make Local", "blender"),
    "object.select_all":              ("Select / Deselect All", "blender"),
    "object.select_grouped":          ("Select Grouped", "blender"),
    "object.select_hierarchy":        ("Select Hierarchy", "blender"),
    "object.select_less":             ("Select Less", "blender"),
    "object.select_linked":           ("Select Linked", "blender"),
    "object.select_mirror":           ("Select Mirror", "blender"),
    "object.select_more":             ("Select More", "blender"),
    "object.parent_set":              ("Set Parent", "blender"),
    "object.parent_clear":            ("Clear Parent", "blender"),
    "object.parent_no_inverse_set":   ("Set Parent (No Inverse)", "blender"),
    "object.vertex_parent_set":       ("Set Vertex Parent", "blender"),
    "object.location_clear":          ("Clear Location", "blender"),
    "object.rotation_clear":          ("Clear Rotation", "blender"),
    "object.scale_clear":             ("Clear Scale", "blender"),
    "object.origin_set":              ("Set Origin", "blender"),
    "object.origin_clear":            ("Clear Origin", "blender"),
    "object.hide_view_set":           ("Hide Objects", "blender"),
    "object.hide_view_clear":         ("Show Hidden Objects", "blender"),
    "object.hide_collection":         ("Hide Collection", "blender"),
    "object.move_to_collection":      ("Move to Collection", "blender"),
    "object.link_to_collection":      ("Link to Collection", "blender"),
    "object.modifier_apply":          ("Apply Modifier", "blender"),
    "object.modifier_copy":           ("Copy Modifier", "blender"),
    "object.modifier_remove":         ("Remove Modifier", "blender"),
    "object.modifier_set_active":     ("Set Active Modifier", "blender"),
    "object.add_modifier_menu":       ("Add Modifier Menu", "blender"),
    "object.subdivision_set":         ("Set Subdivision Level", "blender"),
    "object.voxel_remesh":            ("Voxel Remesh", "blender"),
    "object.voxel_size_edit":         ("Edit Voxel Size", "blender"),
    "object.constraint_add_with_targets": ("Add Constraint (with Targets)", "blender"),
    "object.constraints_clear":       ("Clear Constraints", "blender"),
    "object.track_set":               ("Set Track", "blender"),
    "object.track_clear":             ("Clear Track", "blender"),
    "object.transfer_mode":           ("Transfer Mode", "blender"),
    "object.data_transfer":           ("Transfer Data", "blender"),
    "object.shaderfx_copy":           ("Copy Shader Effect", "blender"),
    "object.shaderfx_remove":         ("Remove Shader Effect", "blender"),
    "object.vertex_group_remove_from":("Remove from Vertex Group", "blender"),
    "object.transform_axis_target":   ("Transform Axis Target", "blender"),
    "object.mode_set":                ("Set Mode", "blender"),
    "object.metaball_add":            ("Add Metaball", "blender"),
    "object.gpencil_modifier_apply":  ("Apply GPencil Modifier", "bforartists"),
    "object.gpencil_modifier_copy":   ("Copy GPencil Modifier", "bforartists"),
    "object.gpencil_modifier_remove": ("Remove GPencil Modifier", "bforartists"),

    # ---- Mesh ----
    "mesh.duplicate_move":            ("Duplicate Mesh", "blender"),
    "mesh.extrude_region_move":       ("Extrude Region", "blender"),
    "mesh.extrude_faces_move":        ("Extrude Faces", "blender"),
    "mesh.extrude_edges_move":        ("Extrude Edges", "blender"),
    "mesh.extrude_vertices_move":     ("Extrude Vertices", "blender"),
    "mesh.inset":                     ("Inset Faces", "blender"),
    "mesh.bevel":                     ("Bevel", "blender"),
    "mesh.loopcut":                   ("Loop Cut", "blender"),
    "mesh.offset_edge_loops_slide":   ("Offset Edge Loops", "blender"),
    "mesh.spin":                      ("Spin", "blender"),
    "mesh.knife_tool":                ("Knife", "blender"),
    "mesh.bisect":                    ("Bisect", "blender"),
    "mesh.fill":                      ("Fill", "blender"),
    "mesh.fill_grid":                 ("Grid Fill", "blender"),
    "mesh.bridge_edge_loops":         ("Bridge Edge Loops", "blender"),
    "mesh.separate":                  ("Separate", "blender"),
    "mesh.split":                     ("Split", "blender"),
    "mesh.merge":                     ("Merge", "blender"),
    "mesh.vertices_smooth":           ("Smooth Vertices", "blender"),
    "mesh.edge_face_add":             ("Make Edge / Face", "blender"),
    "mesh.flip_normals":              ("Flip Normals", "blender"),
    "mesh.normals_make_consistent":   ("Make Normals Consistent", "blender"),
    "mesh.mark_seam":                 ("Mark Seam", "blender"),
    "mesh.mark_sharp":                ("Mark Sharp", "blender"),
    "mesh.vert_connect_path":         ("Connect Vertex Path", "blender"),
    "mesh.tris_convert_to_quads":     ("Tris to Quads", "blender"),
    "mesh.dissolve_contextual_bfa":   ("Dissolve (Contextual BFA)", "bforartists"),
    "mesh.delete":                    ("Delete", "blender"),
    "mesh.dissolve_verts":            ("Dissolve Vertices", "blender"),
    "mesh.dissolve_edges":            ("Dissolve Edges", "blender"),
    "mesh.dissolve_faces":            ("Dissolve Faces", "blender"),
    "mesh.edge_collapse":             ("Collapse Edge", "blender"),
    "mesh.delete_edgeloop":           ("Delete Edge Loop", "blender"),
    "mesh.select_all":                ("Select / Deselect All", "blender"),
    "mesh.select_more":               ("Select More", "blender"),
    "mesh.select_less":               ("Select Less", "blender"),
    "mesh.select_linked":             ("Select Linked", "blender"),
    "mesh.select_linked_pick":        ("Select Linked (Pick)", "blender"),
    "mesh.select_similar":            ("Select Similar", "blender"),
    "mesh.select_mode":               ("Set Select Mode", "blender"),
    "mesh.select_loop_adjacent_region": ("Select Loop Adjacent Region", "blender"),
    "mesh.select_mirror":             ("Select Mirror", "blender"),
    "mesh.select_non_manifold":       ("Select Non-Manifold", "blender"),
    "mesh.select_next_item":          ("Select Next Element", "blender"),
    "mesh.select_prev_item":          ("Select Previous Element", "blender"),
    "mesh.shortest_path_pick":        ("Shortest Path Pick", "blender"),
    "mesh.hide":                      ("Hide Mesh", "blender"),
    "mesh.reveal":                    ("Reveal Hidden Mesh", "blender"),
    "mesh.primitive_plane_add":       ("Add Plane", "blender"),
    "mesh.primitive_cube_add":        ("Add Cube", "blender"),
    "mesh.primitive_circle_add":      ("Add Circle", "blender"),
    "mesh.primitive_uv_sphere_add":   ("Add UV Sphere", "blender"),
    "mesh.primitive_ico_sphere_add":  ("Add Ico Sphere", "blender"),
    "mesh.primitive_cylinder_add":    ("Add Cylinder", "blender"),
    "mesh.primitive_cone_add":        ("Add Cone", "blender"),
    "mesh.primitive_torus_add":       ("Add Torus", "blender"),
    "mesh.primitive_grid_add":        ("Add Grid", "blender"),
    "mesh.primitive_monkey_add":      ("Add Monkey", "blender"),

    # ---- Curve ----
    "curve.duplicate_move":           ("Duplicate Curve", "blender"),
    "curve.extrude_move":             ("Extrude Curve", "blender"),
    "curve.make_segment":             ("Make Segment", "blender"),
    "curve.split":                    ("Split Curve", "blender"),
    "curve.separate":                 ("Separate Curve", "blender"),
    "curve.dissolve_verts":           ("Dissolve Vertices", "blender"),
    "curve.vertex_add":               ("Add Vertex", "blender"),
    "curve.pen":                      ("Curve Pen", "blender"),
    "curve.draw":                     ("Draw Curve", "blender"),
    "curve.select_all":               ("Select / Deselect All", "blender"),
    "curve.select_more":              ("Select More", "blender"),
    "curve.select_less":              ("Select Less", "blender"),
    "curve.select_linked":            ("Select Linked", "blender"),
    "curve.select_linked_pick":       ("Select Linked (Pick)", "blender"),
    "curve.select_similar":           ("Select Similar", "blender"),
    "curve.select_row":               ("Select Row", "blender"),
    "curve.shortest_path_pick":       ("Shortest Path Pick", "blender"),
    "curve.handle_type_set":          ("Set Handle Type", "blender"),
    "curve.cyclic_toggle":            ("Toggle Cyclic", "blender"),
    "curve.normals_make_consistent":  ("Make Normals Consistent", "blender"),
    "curve.tilt_clear":               ("Clear Tilt", "blender"),
    "curve.hide":                     ("Hide Curve", "blender"),
    "curve.reveal":                   ("Reveal Hidden Curve", "blender"),

    # ---- Armature ----
    "armature.bone_primitive_add":    ("Add Bone", "blender"),
    "armature.duplicate_move":        ("Duplicate Bone", "blender"),
    "armature.extrude_move":          ("Extrude Bone", "blender"),
    "armature.extrude_forked":        ("Extrude Forked", "blender"),
    "armature.click_extrude":         ("Click Extrude", "blender"),
    "armature.fill":                  ("Fill Bone", "blender"),
    "armature.split":                 ("Split Bone", "blender"),
    "armature.separate":              ("Separate Armature", "blender"),
    "armature.dissolve":              ("Dissolve Bone", "blender"),
    "armature.delete":                ("Delete Selected Bone(s)", "blender"),
    "armature.switch_direction":      ("Switch Direction", "blender"),
    "armature.select_all":            ("Select / Deselect All", "blender"),
    "armature.select_more":           ("Select More", "blender"),
    "armature.select_less":           ("Select Less", "blender"),
    "armature.select_linked":         ("Select Linked", "blender"),
    "armature.select_linked_pick":    ("Select Linked (Pick)", "blender"),
    "armature.select_similar":        ("Select Similar", "blender"),
    "armature.select_hierarchy":      ("Select Hierarchy", "blender"),
    "armature.select_mirror":         ("Select Mirror", "blender"),
    "armature.shortest_path_pick":    ("Shortest Path Pick", "blender"),
    "armature.parent_set":            ("Set Parent", "blender"),
    "armature.parent_clear":          ("Clear Parent", "blender"),
    "armature.calculate_roll":        ("Calculate Roll", "blender"),
    "armature.roll_clear":            ("Clear Roll", "blender"),
    "armature.align":                 ("Align Bones", "blender"),
    "armature.assign_to_collection":  ("Assign to Collection", "blender"),
    "armature.move_to_collection":    ("Move to Collection", "blender"),
    "armature.hide":                  ("Hide Bone", "blender"),
    "armature.reveal":                ("Reveal Hidden Bone", "blender"),

    # ---- Pose ----
    "pose.copy":                      ("Copy Pose", "blender"),
    "pose.paste":                     ("Paste Pose", "blender"),
    "pose.push":                      ("Push Pose", "blender"),
    "pose.relax":                     ("Relax Pose", "blender"),
    "pose.breakdown":                 ("Pose Breakdown", "blender"),
    "pose.blend_to_neighbor":         ("Blend to Neighbor", "blender"),
    "pose.quaternions_flip":          ("Flip Quaternions", "blender"),
    "pose.select_all":                ("Select / Deselect All", "blender"),
    "pose.select_grouped":            ("Select Grouped", "blender"),
    "pose.select_hierarchy":          ("Select Hierarchy", "blender"),
    "pose.select_linked":             ("Select Linked", "blender"),
    "pose.select_linked_pick":        ("Select Linked (Pick)", "blender"),
    "pose.select_mirror":             ("Select Mirror", "blender"),
    "pose.select_parent":             ("Select Parent", "blender"),
    "pose.loc_clear":                 ("Clear Pose Location", "blender"),
    "pose.rot_clear":                 ("Clear Pose Rotation", "blender"),
    "pose.scale_clear":               ("Clear Pose Scale", "blender"),
    "pose.ik_add":                    ("Add IK", "blender"),
    "pose.ik_clear":                  ("Clear IK", "blender"),
    "pose.constraint_add_with_targets": ("Add Constraint (with Targets)", "blender"),
    "pose.constraints_clear":         ("Clear Constraints", "blender"),
    "pose.rotation_mode_set":         ("Set Rotation Mode", "blender"),
    "pose.hide":                      ("Hide Bone", "blender"),
    "pose.reveal":                    ("Reveal Hidden Bone", "blender"),
    "poselib.apply_pose_asset":       ("Apply Pose Asset", "blender"),
    "poselib.blend_pose_asset":       ("Blend Pose Asset", "blender"),

    # ---- Transform ----
    "transform.translate":            ("Move / Grab", "blender"),
    "transform.rotate":               ("Rotate", "blender"),
    "transform.resize":               ("Scale", "blender"),
    "transform.mirror":               ("Mirror", "blender"),
    "transform.bend":                 ("Bend", "blender"),
    "transform.shear":                ("Shear", "blender"),
    "transform.tosphere":             ("To Sphere", "blender"),
    "transform.push_pull":            ("Push / Pull", "blender"),
    "transform.shrink_fatten":        ("Shrink / Fatten", "blender"),
    "transform.tilt":                 ("Tilt", "blender"),
    "transform.vertex_random":        ("Randomize Vertices", "blender"),
    "transform.edge_slide":           ("Edge Slide", "blender"),
    "transform.vert_slide":           ("Vertex Slide", "blender"),
    "transform.edge_crease":          ("Edge Crease", "blender"),
    "transform.bbone_resize":         ("BBone Resize", "blender"),
    "transform.skin_resize":          ("Skin Resize", "blender"),
    "transform.seq_slide":            ("Sequence Slide", "blender"),
    "transform.transform":            ("Transform", "blender"),
    "transform.from_gizmo":           ("Transform from Gizmo", "blender"),
    "transform.create_orientation":   ("Create Orientation", "blender"),
    "tool_settings.use_proportional_edit": ("Toggle Proportional Edit", "blender"),
    "tool_settings.use_proportional_connected": ("Proportional Edit Connected", "blender"),
    "tool_settings.proportional_edit_falloff": ("Proportional Falloff", "blender"),
    "tool_settings.use_snap":         ("Toggle Snap", "blender"),
    "tool_settings.transform_pivot_point": ("Set Pivot Point", "blender"),

    # ---- Sculpt ----
    "sculpt.brush_stroke":            ("Sculpt Brush Stroke", "blender"),
    "sculpt.detail_flood_fill":       ("Detail Flood Fill", "blender"),
    "sculpt.dyntopo_detail_size_edit":("Edit Dyntopo Detail Size", "blender"),
    "sculpt.set_pivot_position":      ("Set Pivot Position", "blender"),
    "sculpt.expand":                  ("Sculpt Expand", "blender"),
    "sculpt.mesh_filter":             ("Mesh Filter", "blender"),
    "sculpt.cloth_filter":            ("Cloth Filter", "blender"),
    "sculpt.color_filter":            ("Color Filter", "blender"),
    "sculpt.mask_by_color":           ("Mask by Color", "blender"),
    "sculpt.face_set_edit":           ("Edit Face Set", "blender"),
    "sculpt.face_set_change_visibility": ("Change Face Set Visibility", "blender"),
    "sculpt.face_set_box_gesture":    ("Face Set Box Gesture", "blender"),
    "sculpt.face_set_lasso_gesture":  ("Face Set Lasso Gesture", "blender"),
    "sculpt.face_set_line_gesture":   ("Face Set Line Gesture", "blender"),
    "sculpt.face_set_polyline_gesture": ("Face Set Polyline Gesture", "blender"),
    "sculpt.trim_box_gesture":        ("Trim Box Gesture", "blender"),
    "sculpt.trim_lasso_gesture":      ("Trim Lasso Gesture", "blender"),
    "sculpt.trim_line_gesture":       ("Trim Line Gesture", "blender"),
    "sculpt.trim_polyline_gesture":   ("Trim Polyline Gesture", "blender"),
    "sculpt.project_line_gesture":    ("Project Line Gesture", "blender"),
    "sculpt.uv_sculpt_grab":          ("UV Sculpt Grab", "blender"),
    "sculpt.uv_sculpt_pinch":         ("UV Sculpt Pinch", "blender"),
    "sculpt.uv_sculpt_relax":         ("UV Sculpt Relax", "blender"),

    # ---- Paint ----
    "paint.image_paint":              ("Image Paint", "blender"),
    "paint.vertex_paint":             ("Vertex Paint", "blender"),
    "paint.weight_paint":             ("Weight Paint", "blender"),
    "paint.brush_colors_flip":        ("Flip Brush Colors", "blender"),
    "paint.sample_color":             ("Sample Color", "blender"),
    "paint.grab_clone":               ("Grab Clone", "blender"),
    "paint.vertex_color_set":         ("Set Vertex Color", "blender"),
    "paint.weight_set":               ("Set Weight", "blender"),
    "paint.weight_gradient":          ("Weight Gradient", "blender"),
    "paint.weight_sample":            ("Sample Weight", "blender"),
    "paint.weight_sample_group":      ("Sample Weight Group", "blender"),
    "paint.face_select_all":          ("Select / Deselect All Faces", "blender"),
    "paint.face_select_linked":       ("Select Linked Faces", "blender"),
    "paint.face_select_linked_pick":  ("Select Linked (Pick)", "blender"),
    "paint.face_select_loop":         ("Select Face Loop", "blender"),
    "paint.face_select_more":         ("Select More Faces", "blender"),
    "paint.face_select_less":         ("Select Less Faces", "blender"),
    "paint.face_select_hide":         ("Hide Faces", "blender"),
    "paint.face_vert_reveal":         ("Reveal Faces/Verts", "blender"),
    "paint.vert_select_all":          ("Select / Deselect All Vertices", "blender"),
    "paint.vert_select_linked":       ("Select Linked Vertices", "blender"),
    "paint.vert_select_linked_pick":  ("Select Linked Vertex (Pick)", "blender"),
    "paint.vert_select_loop":         ("Select Vertex Loop", "blender"),
    "paint.vert_select_more":         ("Select More Vertices", "blender"),
    "paint.vert_select_less":         ("Select Less Vertices", "blender"),
    "paint.vert_select_hide":         ("Hide Vertices", "blender"),
    "paint.mask_flood_fill":          ("Mask Flood Fill", "blender"),
    "paint.mask_box_gesture":         ("Mask Box", "blender"),
    "paint.mask_lasso_gesture":       ("Mask Lasso", "blender"),
    "paint.mask_line_gesture":        ("Mask Line", "blender"),
    "paint.mask_polyline_gesture":    ("Mask Polyline", "blender"),
    "paint.hide_show":                ("Hide / Show", "blender"),
    "paint.hide_show_all":            ("Hide / Show All", "blender"),
    "paint.hide_show_lasso_gesture":  ("Hide / Show Lasso", "blender"),
    "paint.hide_show_line_gesture":   ("Hide / Show Line", "blender"),
    "paint.hide_show_polyline_gesture": ("Hide / Show Polyline", "blender"),
    "paint.visibility_filter":        ("Visibility Filter", "blender"),

    # ---- Animation ----
    "anim.keyframe_insert":           ("Insert Keyframe", "blender"),
    "anim.keyframe_insert_menu":      ("Insert Keyframe (Menu)", "blender"),
    "anim.keyframe_delete":           ("Delete Keyframe", "blender"),
    "anim.keyframe_insert_button":    ("Insert Keyframe (Button)", "blender"),
    "anim.keyframe_delete_button":    ("Delete Keyframe (Button)", "blender"),
    "anim.keyframe_clear_button":     ("Clear Keyframe (Button)", "blender"),
    "anim.keyframe_delete_vse":       ("Delete Keyframe (VSE)", "blender"),
    "anim.keying_set_active_set":     ("Set Active Keying Set", "blender"),
    "anim.keyingset_button_add":      ("Add to Keying Set", "blender"),
    "anim.keyingset_button_remove":   ("Remove from Keying Set", "blender"),
    "anim.change_frame":              ("Change Frame", "blender"),
    "anim.start_frame_set":           ("Set Start Frame", "blender"),
    "anim.end_frame_set":             ("Set End Frame", "blender"),
    "anim.previewrange_set":          ("Set Preview Range", "blender"),
    "anim.previewrange_clear":        ("Clear Preview Range", "blender"),
    "anim.driver_button_add":         ("Add Driver", "blender"),
    "anim.driver_button_remove":      ("Remove Driver", "blender"),
    "anim.channels_click":            ("Click Channel", "blender"),
    "anim.channels_select_all":       ("Select / Deselect All Channels", "blender"),
    "anim.channels_select_box":       ("Box Select Channels", "blender"),
    "anim.channels_select_filter":    ("Filter Channels", "blender"),
    "anim.channels_collapse":         ("Collapse Channels", "blender"),
    "anim.channels_expand":           ("Expand Channels", "blender"),
    "anim.channels_move":             ("Move Channel", "blender"),
    "anim.channels_group":            ("Group Channels", "blender"),
    "anim.channels_ungroup":          ("Ungroup Channels", "blender"),
    "anim.channels_delete":           ("Delete Channel", "blender"),
    "anim.channels_rename":           ("Rename Channel", "blender"),
    "anim.channels_editable_toggle":  ("Toggle Channel Editable", "blender"),
    "anim.channels_setting_toggle":   ("Toggle Channel Setting", "blender"),
    "anim.channels_setting_enable":   ("Enable Channel Setting", "blender"),
    "anim.channels_setting_disable":  ("Disable Channel Setting", "blender"),
    "anim.channels_view_selected":    ("View Selected Channel", "blender"),
    "screen.animation_play":          ("Play / Pause Animation", "blender"),
    "screen.animation_cancel":        ("Stop Animation", "blender"),
    "screen.frame_jump":              ("Jump to Frame", "blender"),
    "screen.frame_offset":            ("Offset Frame", "blender"),
    "screen.keyframe_jump":           ("Jump to Keyframe", "blender"),

    # ---- Action Editor ----
    "action.select_all":              ("Select / Deselect All", "blender"),
    "action.select_box":              ("Box Select", "blender"),
    "action.select_circle":           ("Circle Select", "blender"),
    "action.select_lasso":            ("Lasso Select", "blender"),
    "action.select_column":           ("Select Column", "blender"),
    "action.select_linked":           ("Select Linked", "blender"),
    "action.select_more":             ("Select More", "blender"),
    "action.select_less":             ("Select Less", "blender"),
    "action.select_leftright":        ("Select Left/Right", "blender"),
    "action.keyframe_insert":         ("Insert Keyframe", "blender"),
    "action.duplicate_move":          ("Duplicate Keyframe", "blender"),
    "action.delete":                  ("Delete Keyframe", "blender"),
    "action.copy":                    ("Copy Keyframe", "blender"),
    "action.paste":                   ("Paste Keyframe", "blender"),
    "action.mirror":                  ("Mirror Keyframe", "blender"),
    "action.snap":                    ("Snap Keyframe", "blender"),
    "action.handle_type":             ("Set Handle Type", "blender"),
    "action.interpolation_type":      ("Set Interpolation", "blender"),
    "action.easing_type":             ("Set Easing", "blender"),
    "action.extrapolation_type":      ("Set Extrapolation", "blender"),
    "action.keyframe_type":           ("Set Keyframe Type", "blender"),
    "action.bake_keys":               ("Bake Keys", "blender"),
    "action.frame_jump":              ("Jump to Keyframe", "blender"),
    "action.view_all":                ("View All", "blender"),
    "action.view_selected":           ("View Selected", "blender"),
    "action.view_frame":              ("View Frame", "blender"),
    "action.previewrange_set":        ("Set Preview Range", "blender"),

    # ---- NLA ----
    "nla.select_all":                 ("Select / Deselect All", "blender"),
    "nla.select_box":                 ("Box Select", "blender"),
    "nla.select_leftright":           ("Select Left/Right", "blender"),
    "nla.duplicate_move":             ("Duplicate Strip", "blender"),
    "nla.duplicate_linked_move":      ("Duplicate Linked Strip", "blender"),
    "nla.duplicate":                  ("Duplicate Strips", "blender"),
    "nla.delete":                     ("Delete Strip", "blender"),
    "nla.split":                      ("Split Strip", "blender"),
    "nla.meta_add":                   ("Add Meta Strip", "blender"),
    "nla.meta_remove":                ("Remove Meta Strip", "blender"),
    "nla.mute_toggle":                ("Mute/Unmute Strip", "blender"),
    "nla.swap":                       ("Swap Strips", "blender"),
    "nla.move_up":                    ("Move Strip Up", "blender"),
    "nla.move_down":                  ("Move Strip Down", "blender"),
    "nla.snap":                       ("Snap Strip", "blender"),
    "nla.apply_scale":                ("Apply Scale", "blender"),
    "nla.clear_scale":                ("Clear Scale", "blender"),
    "nla.actionclip_add":             ("Add Action Clip", "blender"),
    "nla.soundclip_add":              ("Add Sound Clip", "blender"),
    "nla.transition_add":             ("Add Transition", "blender"),
    "nla.tracks_add":                 ("Add Track", "blender"),
    "nla.tracks_delete":              ("Delete Track", "blender"),
    "nla.tweakmode_enter":            ("Enter Tweak Mode", "blender"),
    "nla.tweakmode_exit":             ("Exit Tweak Mode", "blender"),
    "nla.make_single_user":           ("Make Single User", "blender"),
    "nla.view_all":                   ("View All", "blender"),
    "nla.view_selected":              ("View Selected", "blender"),
    "nla.view_frame":                 ("View Frame", "blender"),

    # ---- Node Editor ----
    "node.duplicate_move":            ("Duplicate Node", "blender"),
    "node.duplicate_move_keep_inputs":("Duplicate Node (Keep Inputs)", "blender"),
    "node.duplicate_move_linked":     ("Duplicate Node (Linked)", "blender"),
    "node.delete":                    ("Delete Node", "blender"),
    "node.delete_reconnect":          ("Delete and Reconnect", "blender"),
    "node.delete_copy_reconnect":     ("Delete Copy Reconnect", "bforartists"),
    "node.mute_toggle":               ("Mute / Unmute Node", "blender"),
    "node.hide_toggle":               ("Hide / Show Node", "blender"),
    "node.preview_toggle":            ("Toggle Node Preview", "blender"),
    "node.hide_socket_toggle":        ("Hide Socket Toggle", "blender"),
    "node.translate_attach":          ("Move and Attach Node", "blender"),
    "node.move_detach_links":         ("Move and Detach Links", "blender"),
    "node.resize":                    ("Resize Node", "blender"),
    "node.find_node":                 ("Find Node", "blender"),
    "node.select":                    ("Select Node", "blender"),
    "node.select_all":                ("Select / Deselect All", "blender"),
    "node.select_box":                ("Box Select Nodes", "blender"),
    "node.select_circle":             ("Circle Select Nodes", "blender"),
    "node.select_lasso":              ("Lasso Select Nodes", "blender"),
    "node.select_linked_from":        ("Select Linked From", "blender"),
    "node.select_linked_to":          ("Select Linked To", "blender"),
    "node.select_grouped":            ("Select Grouped", "blender"),
    "node.select_same_type_step":     ("Select Same Type Step", "blender"),
    "node.select_link_viewer":        ("Select Link Viewer", "blender"),
    "node.link":                      ("Link Nodes", "blender"),
    "node.link_make":                 ("Make Links", "blender"),
    "node.links_cut":                 ("Cut Links", "blender"),
    "node.links_mute":                ("Mute Links", "blender"),
    "node.detach":                    ("Detach Node", "blender"),
    "node.add_reroute":               ("Add Reroute", "blender"),
    "node.parent_set":                ("Set Parent Node", "blender"),
    "node.group_make":                ("Make Group", "blender"),
    "node.group_ungroup":             ("Ungroup", "blender"),
    "node.group_separate":            ("Separate Group", "blender"),
    "node.group_edit":                ("Edit Group", "blender"),
    "node.group_enter_exit":          ("Enter / Exit Group", "blender"),
    "node.join":                      ("Join Nodes in Frame", "blender"),
    "node.join_named":                ("Join Named Nodes", "blender"),
    "node.join_nodes":                ("Join Nodes", "blender"),
    "node.view_all":                  ("View All Nodes", "blender"),
    "node.view_selected":             ("View Selected Nodes", "blender"),
    "node.backimage_fit":             ("Fit Background Image", "blender"),
    "node.backimage_move":            ("Move Background Image", "blender"),
    "node.backimage_zoom":            ("Zoom Background Image", "blender"),
    "node.backimage_sample":          ("Sample Background Image", "blender"),
    "node.viewer_border":             ("Viewer Region", "blender"),
    "node.clear_viewer_border":       ("Clear Viewer Region", "blender"),
    "node.read_viewlayers":           ("Read View Layers", "blender"),
    "node.render_changed":            ("Render Changed", "blender"),
    "node.connect_to_output":         ("Connect to Output", "blender"),
    "node.viewer_shortcut_get":       ("Get Viewer Shortcut", "blender"),
    "node.viewer_shortcut_set":       ("Set Viewer Shortcut", "blender"),
    "node.clipboard_copy":            ("Copy Node", "blender"),
    "node.clipboard_paste":           ("Paste Node", "blender"),
    "node.move_detach_links_release": ("Move Detach Links (Release)", "blender"),

    # ---- UV Editor ----
    "uv.select":                      ("Select UV", "blender"),
    "uv.select_all":                  ("Select / Deselect All UV", "blender"),
    "uv.select_box":                  ("Box Select UV", "blender"),
    "uv.select_circle":               ("Circle Select UV", "blender"),
    "uv.select_lasso":                ("Lasso Select UV", "blender"),
    "uv.select_loop":                 ("Select UV Loop", "blender"),
    "uv.select_edge_ring":            ("Select UV Edge Ring", "blender"),
    "uv.select_linked":               ("Select Linked UV", "blender"),
    "uv.select_linked_pick":          ("Select Linked UV (Pick)", "blender"),
    "uv.select_more":                 ("Select More UV", "blender"),
    "uv.select_less":                 ("Select Less UV", "blender"),
    "uv.select_similar":              ("Select Similar UV", "blender"),
    "uv.select_pinned":               ("Select Pinned UV", "blender"),
    "uv.select_split":                ("Select Split UV", "blender"),
    "uv.select_mode":                 ("Set UV Select Mode", "blender"),
    "uv.shortest_path_pick":          ("Shortest Path Pick UV", "blender"),
    "uv.unwrap":                      ("Unwrap", "blender"),
    "uv.pack_islands":                ("Pack Islands", "blender"),
    "uv.average_islands_scale":       ("Average Islands Scale", "blender"),
    "uv.minimize_stretch":            ("Minimize Stretch", "blender"),
    "uv.stitch":                      ("Stitch", "blender"),
    "uv.pin":                         ("Pin UV", "blender"),
    "uv.rip_move":                    ("Rip UV", "blender"),
    "uv.mark_seam":                   ("Mark UV Seam", "blender"),
    "uv.clear_seam":                  ("Clear UV Seam", "bforartists"),
    "uv.move_on_axis":                ("Move UV on Axis", "blender"),
    "uv.custom_region_set":           ("Set Custom UV Region", "blender"),
    "uv.hide":                        ("Hide UV", "blender"),
    "uv.reveal":                      ("Reveal Hidden UV", "blender"),
    "uv.copy":                        ("Copy UV", "blender"),
    "uv.paste":                       ("Paste UV", "blender"),
    "uv.cursor_set":                  ("Set UV Cursor", "blender"),

    # ---- Sequencer ----
    "sequencer.select":               ("Select Strip", "blender"),
    "sequencer.select_all":           ("Select / Deselect All", "blender"),
    "sequencer.select_box":           ("Box Select Strips", "blender"),
    "sequencer.select_circle":        ("Circle Select Strips", "blender"),
    "sequencer.select_lasso":         ("Lasso Select Strips", "blender"),
    "sequencer.select_more":          ("Select More", "blender"),
    "sequencer.select_less":          ("Select Less", "blender"),
    "sequencer.select_linked":        ("Select Linked", "blender"),
    "sequencer.select_linked_pick":   ("Select Linked (Pick)", "blender"),
    "sequencer.select_handle":        ("Select Handle", "blender"),
    "sequencer.select_side_of_frame": ("Select Side of Frame", "blender"),
    "sequencer.select_grouped":       ("Select Grouped", "blender"),
    "sequencer.duplicate_move":       ("Duplicate Strip", "blender"),
    "sequencer.duplicate_move_linked":("Duplicate Linked Strip", "blender"),
    "sequencer.delete":               ("Delete Strip", "blender"),
    "sequencer.split":                ("Split Strip", "blender"),
    "sequencer.slip":                 ("Slip Strip", "blender"),
    "sequencer.snap":                 ("Snap Strip", "blender"),
    "sequencer.swap":                 ("Swap Strips", "blender"),
    "sequencer.swap_inputs":          ("Swap Inputs", "blender"),
    "sequencer.offset_clear":         ("Clear Strip Offset", "blender"),
    "sequencer.gap_insert":           ("Insert Gap", "blender"),
    "sequencer.gap_remove":           ("Remove Gap", "blender"),
    "sequencer.meta_make":            ("Make Meta Strip", "blender"),
    "sequencer.meta_separate":        ("Separate Meta Strip", "blender"),
    "sequencer.meta_toggle":          ("Toggle Meta Strip", "blender"),
    "sequencer.lock":                 ("Lock Strip", "blender"),
    "sequencer.unlock":               ("Unlock Strip", "blender"),
    "sequencer.mute":                 ("Mute Strip", "blender"),
    "sequencer.unmute":               ("Unmute Strip", "blender"),
    "sequencer.view_all":             ("View All Strips", "blender"),
    "sequencer.view_all_preview":     ("View All (Preview)", "blender"),
    "sequencer.view_selected":        ("View Selected Strips", "blender"),
    "sequencer.view_frame":           ("View Frame", "blender"),
    "sequencer.view_zoom_ratio":      ("Zoom Ratio", "blender"),
    "sequencer.strip_jump":           ("Jump to Strip", "blender"),
    "sequencer.copy":                 ("Copy Strip", "blender"),
    "sequencer.paste":                ("Paste Strip", "blender"),
    "sequencer.images_separate":      ("Separate Images", "blender"),
    "sequencer.reassign_inputs":      ("Reassign Inputs", "blender"),
    "sequencer.connect":              ("Connect Strips", "blender"),
    "sequencer.strip_transform_clear":("Clear Strip Transform", "blender"),
    "sequencer.refresh_all":          ("Refresh All", "blender"),
    "sequencer.reload":               ("Reload Strip", "blender"),
    "sequencer.box_blade":            ("Box Blade", "blender"),

    # ---- Outliner ----
    "outliner.item_activate":         ("Activate Item", "blender"),
    "outliner.select_all":            ("Select / Deselect All", "blender"),
    "outliner.select_box":            ("Box Select", "blender"),
    "outliner.select_walk":           ("Walk Select", "blender"),
    "outliner.show_active":           ("Show Active", "blender"),
    "outliner.collection_objects_select": ("Select Objects", "blender"),
    "outliner.item_rename":           ("Rename Item", "blender"),
    "outliner.delete":                ("Delete Item", "blender"),
    "outliner.collection_new":        ("New Collection", "blender"),
    "outliner.id_copy":               ("Copy ID", "blender"),
    "outliner.id_paste":              ("Paste ID", "blender"),
    "outliner.id_operation":          ("Outliner ID Data Operation", "blender"),
    "outliner.operation":             ("Outliner Operation", "blender"),
    "outliner.show_hierarchy":        ("Show Hierarchy", "blender"),
    "outliner.show_one_level":        ("Show One Level", "blender"),
    "outliner.expanded_toggle":       ("Toggle Expanded", "blender"),
    "outliner.unhide_all":            ("Unhide All", "blender"),
    "outliner.hide":                  ("Hide Item", "blender"),
    "outliner.item_openclose":        ("Open/Close Item", "blender"),
    "outliner.scroll_page":           ("Scroll Page", "blender"),
    "outliner.start_filter":          ("Start Filter", "blender"),
    "outliner.clear_filter":          ("Clear Filter", "blender"),
    "outliner.drivers_add_selected":  ("Add Driver", "blender"),
    "outliner.drivers_delete_selected":("Delete Driver", "blender"),
    "outliner.keyingset_add_selected":("Add to Keying Set", "blender"),
    "outliner.keyingset_remove_selected":("Remove from Keying Set", "blender"),

    # ---- Screen / Window ----
    "screen.area_split":              ("Split Area", "blender"),
    "screen.area_join":               ("Join Areas", "blender"),
    "screen.area_move":               ("Move Area Border", "blender"),
    "screen.area_dupli":              ("Duplicate Area", "blender"),
    "screen.area_swap":               ("Swap Areas", "blender"),
    "screen.area_options":            ("Area Options", "blender"),
    "screen.screen_full_area":        ("Toggle Fullscreen Area", "blender"),
    "screen.region_quadview":         ("Toggle Quad View", "blender"),
    "screen.region_flip":             ("Flip Region", "blender"),
    "screen.region_context_menu":     ("Region Context Menu", "blender"),
    "ed.undo":                        ("Undo", "blender"),
    "ed.redo":                        ("Redo", "blender"),
    "ed.undo_history":                ("Undo History", "blender"),
    "screen.redo_last":               ("Adjust Last Operation", "blender"),
    "screen.repeat_last":             ("Repeat Last", "blender"),
    "screen.repeat_history":          ("Repeat History", "blender"),
    "wm.save_mainfile":               ("Save File", "blender"),
    "wm.save_as_mainfile":            ("Save File As", "blender"),
    "wm.open_mainfile":               ("Open File", "blender"),
    "wm.append":                      ("Append from File", "blender"),
    "wm.link":                        ("Link from File", "blender"),
    "wm.save_homefile":               ("Save Startup File", "blender"),
    "wm.read_homefile":               ("Reload Start-Up File", "blender"),
    "wm.quit_blender":                ("Quit", "blender"),
    "wm.search_menu":                 ("Search Menu", "blender"),
    "wm.toolbar":                     ("Toolbar", "blender"),
    "wm.toolbar_fallback_pie":        ("Toolbar Fallback Pie", "blender"),
    "wm.call_menu":                   ("Call Menu", "blender"),
    "wm.call_menu_pie":               ("Call Pie Menu", "blender"),
    "wm.call_panel":                  ("Call Panel", "blender"),
    "wm.batch_rename":                ("Batch Rename", "blender"),
    "wm.console_toggle":              ("Toggle Console", "bforartists"),
    "wm.window_fullscreen_toggle":    ("Toggle Window Fullscreen", "blender"),
    "wm.window_new":                  ("New Window", "blender"),
    "wm.debug_menu":                  ("Debug Menu", "blender"),
    "screen.workspace_cycle":         ("Cycle Workspace", "blender"),
    "screen.screen_set":              ("Set Screen", "blender"),
    "screen.space_context_cycle":     ("Cycle Space Context", "blender"),
    "screen.space_type_set_or_cycle": ("Set or Cycle Space Type", "blender"),
    "screen.userpref_show":           ("Show Preferences", "blender"),
    "screen.screenshot":              ("Screenshot", "blender"),
    "script.reload":                  ("Reload Scripts", "blender"),
    # ---- Context Operators ----
    "wm.tool_set_by_id":              ("Set Tool by ID", "blender"),
    "wm.tool_set_by_name":            ("Set Tool by Name", "blender"),
    "wm.context_toggle_enum":         ("Context Toggle Enum", "blender"),
    "wm.context_toggle":              ("Context Toggle", "blender"),
    "wm.context_set_boolean":         ("Context Set Boolean", "blender"),
    "wm.context_set_enum":            ("Context Set Enum", "blender"),
    "wm.context_set_float":           ("Context Set Float", "blender"),
    "wm.context_set_int":             ("Context Set Int", "blender"),
    "wm.context_set_string":          ("Context Set String", "blender"),
    "wm.context_set_value":           ("Context Set Value", "blender"),
    "wm.context_set_id":              ("Context Set ID", "blender"),
    "wm.context_scale_float":         ("Context Scale Float", "blender"),
    "wm.context_scale_int":           ("Context Scale Int", "blender"),
    "wm.context_cycle_enum":          ("Context Cycle Enum", "blender"),
    "wm.context_cycle_int":           ("Context Cycle Int", "blender"),
    "wm.context_cycle_array":         ("Context Cycle Array", "blender"),
    "wm.context_menu_enum":           ("Context Menu Enum", "blender"),
    "wm.context_pie_enum":            ("Context Pie Enum", "blender"),
    "wm.context_modal_mouse":         ("Context Modal Mouse", "blender"),
    "wm.context_collection_boolean_set": ("Context Collection Boolean Set", "blender"),

    # ---- Render ----
    "render.render":                  ("Render Image", "blender"),
    "render.play_rendered_anim":      ("Play Rendered Animation", "blender"),
    "render.view_show":               ("Show Render Result", "blender"),
    "render.view_cancel":             ("Cancel Render", "blender"),

    # ---- Particle ----
    "particle.brush_edit":            ("Particle Brush Edit", "blender"),
    "particle.delete":                ("Delete Particle", "blender"),
    "particle.weight_set":            ("Set Particle Weight", "blender"),
    "particle.select_all":            ("Select / Deselect All", "blender"),
    "particle.select_more":           ("Select More", "blender"),
    "particle.select_less":           ("Select Less", "blender"),
    "particle.select_linked":         ("Select Linked", "blender"),
    "particle.select_linked_pick":    ("Select Linked (Pick)", "blender"),
    "particle.hide":                  ("Hide Particle", "blender"),
    "particle.reveal":                ("Reveal Hidden Particle", "blender"),

    # ---- Text Object ----
    "font.text_insert":               ("Insert Text", "blender"),
    "font.delete":                    ("Delete Text", "blender"),
    "font.line_break":                ("Insert Line Break", "blender"),
    "font.move":                      ("Move Cursor", "blender"),
    "font.move_select":               ("Move and Select", "blender"),
    "font.select_all":                ("Select All Text", "blender"),
    "font.select_word":               ("Select Word", "blender"),
    "font.selection_set":             ("Set Selection", "blender"),
    "font.style_toggle":              ("Toggle Style", "blender"),
    "font.change_character":          ("Change Character", "blender"),
    "font.change_spacing":            ("Change Spacing", "blender"),
    "font.text_copy":                 ("Copy Text", "blender"),
    "font.text_cut":                  ("Cut Text", "blender"),
    "font.text_paste":                ("Paste Text", "blender"),

    # ---- Grease Pencil ----
    "grease_pencil.select_all":       ("Select / Deselect All", "blender"),
    "grease_pencil.select_box":       ("Box Select", "blender"),
    "grease_pencil.select_circle":    ("Circle Select", "blender"),
    "grease_pencil.select_lasso":     ("Lasso Select", "blender"),
    "grease_pencil.select_more":      ("Select More", "blender"),
    "grease_pencil.select_less":      ("Select Less", "blender"),
    "grease_pencil.select_linked":    ("Select Linked", "blender"),
    "grease_pencil.select_linked_pick":("Select Linked (Pick)", "blender"),
    "grease_pencil.duplicate_move":   ("Duplicate Stroke", "blender"),
    "grease_pencil.delete":           ("Delete Stroke", "blender"),
    "grease_pencil.dissolve":         ("Dissolve Points", "blender"),
    "grease_pencil.extrude_move":     ("Extrude Points", "blender"),
    "grease_pencil.cyclical_set":     ("Set Cyclic", "blender"),
    "grease_pencil.separate":         ("Separate Strokes", "blender"),
    "grease_pencil.split":            ("Split Strokes", "blender"),
    "grease_pencil.brush_stroke":     ("GP Brush Stroke", "blender"),
    "grease_pencil.sculpt_paint":     ("GP Sculpt Paint", "blender"),
    "grease_pencil.weight_brush_stroke":("GP Weight Brush", "blender"),
    "grease_pencil.vertex_paint":     ("GP Vertex Paint", "blender"),
    "grease_pencil.fill":             ("GP Fill", "blender"),
    "grease_pencil.interpolate":      ("GP Interpolate", "blender"),
    "grease_pencil.interpolate_sequence":("GP Interpolate Sequence", "blender"),
    "gpencil.annotate":               ("Annotate", "blender"),
    "gpencil.annotation_add":         ("Annotation Add New", "blender"),
    "gpencil.annotation_active_frame_delete":("Delete Active Frame", "blender"),

    # ---- Curves (Hair) ----
    "curves.duplicate_move":          ("Duplicate Curves", "blender"),
    "curves.delete":                  ("Delete Curves", "blender"),
    "curves.extrude_move":            ("Extrude Curves", "blender"),
    "curves.split":                   ("Split Curves", "blender"),
    "curves.separate":                ("Separate Curves", "blender"),
    "curves.cyclic_toggle":           ("Toggle Cyclic", "blender"),
    "curves.tilt_clear":              ("Clear Tilt", "blender"),
    "curves.handle_type_set":         ("Set Handle Type", "blender"),
    "curves.draw":                    ("Draw Curves", "blender"),
    "curves.pen":                     ("Curves Pen", "blender"),
    "curves.select_all":              ("Select / Deselect All", "blender"),
    "curves.select_more":             ("Select More", "blender"),
    "curves.select_less":             ("Select Less", "blender"),
    "curves.select_linked":           ("Select Linked", "blender"),
    "curves.select_linked_pick":      ("Select Linked (Pick)", "blender"),
    "curves.set_selection_domain":    ("Set Selection Domain", "blender"),
    "sculpt_curves.brush_stroke":     ("Sculpt Curves Brush", "blender"),
    "sculpt_curves.select_grow":      ("Grow Selection", "blender"),
    "sculpt_curves.min_distance_edit":("Edit Min Distance", "blender"),

    # ---- Bforartists Exclusive ----
    "scene.cic_create_gameisocam":    ("Create Game Iso Camera", "bforartists"),
    "scene.cic_create_trueisocam":    ("Create True Iso Camera", "bforartists"),
    "scene.cic_create_groundplane":   ("Create Ground Plane", "bforartists"),

    # ---- Constraints ----
    "constraint.apply":               ("Apply Constraint", "blender"),
    "constraint.copy":                ("Copy Constraint", "blender"),
    "constraint.delete":              ("Delete Constraint", "blender"),

    # ---- Collections ----
    "collection.create":              ("Create Collection", "blender"),
    "collection.objects_add_active":  ("Add Active to Collection", "blender"),
    "collection.objects_remove":      ("Remove from Collection", "blender"),
    "collection.objects_remove_active":("Remove Active from Collection", "blender"),
    "collection.objects_remove_all":  ("Remove from All Collections", "blender"),

    # ---- Rename ----
    "wm.batch_rename":                ("Batch Rename", "blender"),
    "outliner.item_rename":           ("Rename Item", "blender"),
    "ui.view_item_rename":            ("Rename", "blender"),
    "wm.call_asset_shelf_popover":    ("Asset Shelf Popover", "blender"),
    # Graph Editor
    "graph.select_all":            ("Select All", "blender"),
    "graph.select_box":            ("Box Select", "blender"),
    "graph.select_circle":         ("Circle Select", "blender"),
    "graph.select_lasso":          ("Lasso Select", "blender"),
    "graph.select_column":         ("Select Column", "blender"),
    "graph.select_linked":         ("Select Linked", "blender"),
    "graph.select_more":           ("Select More", "blender"),
    "graph.select_less":           ("Select Less", "blender"),
    "graph.select_leftright":      ("Select Left / Right", "blender"),
    "graph.keyframe_insert":       ("Insert Keyframe", "blender"),
    "graph.duplicate_move":        ("Duplicate", "blender"),
    "graph.delete":                ("Delete", "blender"),
    "graph.copy":                  ("Copy Keyframes", "blender"),
    "graph.paste":                 ("Paste Keyframes", "blender"),
    "graph.mirror":                ("Mirror", "blender"),
    "graph.snap":                  ("Snap Keys", "blender"),
    "graph.handle_type":           ("Set Handle Type", "blender"),
    "graph.interpolation_type":    ("Set Interpolation", "blender"),
    "graph.easing_type":           ("Set Easing", "blender"),
    "graph.extrapolation_type":    ("Set Extrapolation", "blender"),
    "graph.keyframe_type":         ("Set Keyframe Type", "blender"),
    "graph.bake_keys":             ("Bake Keys", "blender"),
    "graph.frame_jump":            ("Jump to Keyframe", "blender"),
    "graph.view_all":              ("View All", "blender"),
    "graph.view_selected":         ("View Selected", "blender"),
    "graph.view_frame":            ("View Frame", "blender"),
    "graph.previewrange_set":      ("Set Preview Range", "blender"),
    "graph.hide":                  ("Hide Curves", "blender"),
    "graph.reveal":                ("Reveal Curves", "blender"),
    "graph.fmodifier_add":         ("Add F-Modifier", "blender"),
    "graph.fmodifier_copy":        ("Copy F-Modifiers", "blender"),
    "graph.fmodifier_paste":       ("Paste F-Modifiers", "blender"),
    "graph.driver_delete_invalid": ("Delete Invalid Drivers", "blender"),
    "graph.decimate":              ("Decimate Keys", "blender"),
    "graph.unbake":                ("Un-Bake Keys", "blender"),
    "graph.keys_to_samples":       ("Keys to Samples", "blender"),
    "graph.samples_to_keys":       ("Samples to Keys", "blender"),
    "graph.sound_to_samples":      ("Sound to Samples", "blender"),
    "graph.euler_filter":          ("Euler Filter", "blender"),
    "graph.clean":                 ("Clean Keyframes", "blender"),
    "graph.smooth":                ("Smooth Keyframes", "blender"),
    "graph.previous_keyframe":     ("Previous Keyframe", "blender"),
    "graph.next_keyframe":         ("Next Keyframe", "blender"),
    # Image Editor — View
    "image.view_all":              ("View All", "blender"),
    "image.view_selected":         ("View Selected", "blender"),
    "image.view_center_cursor":    ("Center View to Cursor", "blender"),
    "image.view_zoom_in":          ("Zoom In", "blender"),
    "image.view_zoom_out":         ("Zoom Out", "blender"),
    "image.view_zoom_ratio":       ("Zoom to Ratio", "blender"),
    "image.view_ndof":             ("NDOF View", "blender"),
    "image.view_pan":              ("Pan View", "blender"),
    # Image Editor — Edit
    "image.flip":                  ("Flip Image", "blender"),
    "image.rotate_orthogonal":     ("Rotate Orthogonal", "blender"),
    "image.invert":                ("Invert Colors", "blender"),
    "image.resize":                ("Resize Image", "blender"),
    "image.crop":                  ("Crop Image", "blender"),
    # Image Editor — File
    "image.new":                   ("New Image", "blender"),
    "image.open":                  ("Open Image", "blender"),
    "image.reload":                ("Reload Image", "blender"),
    "image.save":                  ("Save Image", "blender"),
    "image.save_as":               ("Save Image As", "blender"),
    "image.pack":                  ("Pack Image", "blender"),
    # Video Sequencer — View
    "sequencer.view_ghost_border": ("Set Ghost Border", "blender"),

    # Bforartists — User Settings (bfa.* operators with disambiguated names)
    "bfa.reset_animation":          ("Reset Animation", "bforartists"),
    "bfa.reset_toolbar_animation":  ("Reset Animation Toolbar", "bforartists"),
    "bfa.reset_edit":               ("Reset Edit", "bforartists"),
    "bfa.reset_toolbar_edit":       ("Reset Edit Toolbar", "bforartists"),
    "bfa.reset_files":              ("Reset Files", "bforartists"),
    "bfa.reset_toolbar_files":      ("Reset Files Toolbar", "bforartists"),
    "bfa.reset_image":              ("Reset Image", "bforartists"),
    "bfa.reset_toolbar_image":      ("Reset Image Toolbar", "bforartists"),
    "bfa.reset_meshedit":           ("Reset Mesh Edit", "bforartists"),
    "bfa.reset_toolbar_meshedit":   ("Reset Mesh Edit Toolbar", "bforartists"),
    "bfa.reset_misc":               ("Reset Misc", "bforartists"),
    "bfa.reset_toolbar_misc":       ("Reset Misc Toolbar", "bforartists"),
    "bfa.reset_primitives":         ("Reset Primitives", "bforartists"),
    "bfa.reset_toolbar_primitives": ("Reset Primitives Toolbar", "bforartists"),
    "bfa.reset_topbar":             ("Reset All", "bforartists"),
    "bfa.reset_toolbar":            ("Reset All Toolbars", "bforartists"),
    "bfa.reset_tools":              ("Reset Tools", "bforartists"),
    "bfa.reset_toolbar_tools":      ("Reset Tools Toolbar", "bforartists"),

    # ---- 3D View ----
    "view3d.view_orbit":                ("Orbit Viewport", "blender"),
    "view3d.view_roll":                 ("Roll Viewport", "blender"),
    "view3d.view_pan":                  ("Pan Viewport", "blender"),
    "view3d.zoom":                      ("Zoom Viewport", "blender"),
    "view3d.dolly":                     ("Dolly Viewport", "blender"),
    "view3d.view_center_cursor":        ("Center View to Cursor", "blender"),
    "view3d.view_center_pick":          ("Center View to Mouse", "blender"),
    "view3d.view_selected":             ("View Selected", "blender"),
    "view3d.view_all":                  ("View All", "blender"),
    "view3d.view_camera":               ("View Camera", "blender"),
    "view3d.navigate":                  ("Navigate", "blender"),
    "view3d.fly":                       ("Fly Navigation", "blender"),
    "view3d.walk":                      ("Walk Navigation", "blender"),
    "view3d.zoom_border":               ("Zoom Border", "blender"),
    "view3d.zoom_camera_1_to_1":        ("Zoom Camera 1:1", "blender"),
    "view3d.view_axis":                 ("View Axis", "blender"),
    "view3d.view_persportho":           ("Toggle Perspective / Orthographic", "blender"),
    "view3d.localview":                 ("Toggle Local View", "blender"),
    "view3d.localview_remove_from":     ("Remove From Local View", "blender"),
    "view3d.ndof_orbit":                ("NDOF Orbit", "blender"),
    "view3d.ndof_orbit_zoom":           ("NDOF Orbit Zoom", "blender"),
    "view3d.ndof_pan":                  ("NDOF Pan", "blender"),
    "view3d.ndof_all":                  ("NDOF All", "blender"),
    "view3d.smoothview":                ("Smooth View", "blender"),
    "view3d.toggle_shading":            ("Toggle Shading Mode", "blender"),
    "view3d.wireframe_toggle":          ("Toggle Wireframe", "blender"),
    "view3d.xray_toggle":               ("Toggle X-Ray", "blender"),
    "view3d.overlay_toggle":            ("Toggle Overlays", "blender"),
    "view3d.toggle_matcap_flip":        ("Flip MatCap", "blender"),
    "view3d.view_lock_to_active":       ("Lock View to Active", "blender"),
    "view3d.view_lock_clear":           ("Clear View Lock", "blender"),
    "view3d.clip_border":               ("Set Clip Border", "blender"),
    "view3d.render_border":             ("Set Render Border", "blender"),
    "view3d.clear_render_border":       ("Clear Render Border", "blender"),
    "view3d.cursor3d":                  ("Set 3D Cursor", "blender"),
    "view3d.snap_cursor_to_selected":   ("Snap Cursor to Selected", "blender"),
    "view3d.snap_cursor_to_center":     ("Snap Cursor to Center", "blender"),
    "view3d.snap_cursor_to_active":     ("Snap Cursor to Active", "blender"),
    "view3d.snap_cursor_to_grid":       ("Snap Cursor to Grid", "blender"),
    "view3d.snap_selected_to_cursor":   ("Snap Selected to Cursor", "blender"),
    "view3d.snap_selected_to_grid":     ("Snap Selected to Grid", "blender"),
    "view3d.select":                    ("Select", "blender"),
    "view3d.select_box":                ("Box Select", "blender"),
    "view3d.select_circle":             ("Circle Select", "blender"),
    "view3d.select_lasso":              ("Lasso Select", "blender"),
    "view3d.select_menu":               ("Select Menu", "blender"),
    "view3d.object_mode_pie_or_toggle": ("Mode Pie / Toggle", "blender"),
    "view3d.move":                      ("Move (Viewport)", "blender"),
    "view3d.rotate":                    ("Rotate (Viewport)", "blender"),
    "view3d.scale":                     ("Scale (Viewport)", "blender"),

    # ---- Window Manager ----
    "wm.call_menu_pie":                 ("Call Pie Menu", "blender"),
    "wm.call_menu":                     ("Call Menu", "blender"),
    "wm.call_panel":                    ("Call Panel", "blender"),

}


BFA_ONLY_OPS = {op for op, (_, src) in FRIENDLY_NAMES.items() if src == "bforartists"}


_dup_names = None  # lazy: friendly labels shared by 2+ operators


def _raw_friendly(operator_id: str) -> str | None:
    entry = FRIENDLY_NAMES.get(operator_id)
    if entry:
        return entry[0]
    # Fall back to the operator's bl_label from Blender's RNA system
    try:
        module, func = operator_id.split(".", 1)
        op_fn = getattr(getattr(bpy.ops, module), func)
        name = op_fn.get_rna_type().name
        # Blender's own bl_label for several select_all operators is the
        # cramped "(De)select All" — normalise it to the curated style.
        if name == "(De)select All":
            name = "Select / Deselect All"
        return name
    except Exception:
        return None


def _build_dup_names() -> dict:
    """{friendly label: [op_ids]} for labels used by more than one operator —
    walked over every registered operator plus the curated table, once per
    session."""
    by_name = {}

    def _tally(op_id, name):
        if name:
            by_name.setdefault(name, []).append(op_id)

    seen = set()
    try:
        from ..operator_discovery import _iter_bpy_ops as _ibo
        for module, func in _ibo():
            try:
                op_id = f"{module}.{func}"
                seen.add(op_id)
                _tally(op_id, _raw_friendly(op_id))
            except Exception:
                continue
    except Exception:
        pass
    for op_id in FRIENDLY_NAMES:
        if op_id not in seen:
            _tally(op_id, _raw_friendly(op_id))
    return {n: ids for n, ids in by_name.items() if len(ids) > 1}


_TOKEN_PRETTY = {
    "vert": "Vertex", "verts": "Vertex", "obj": "Object", "uv": "UV",
    "fcurve": "F-Curve", "gp": "Grease Pencil",
}


def qualify_op_label(operator_id: str, name: str) -> str:
    """Append the operator's module ("Select All (NLA)") when the friendly
    label is shared by several operators — same treatment as the duplicated
    menu names. When the collision is WITHIN one module (paint.face_select_more
    vs paint.vert_select_more), the module alone can't tell them apart, so the
    distinguishing token(s) of the function name are added too:
    "Select More (Paint Face)" / "Select More (Paint Vertex)"."""
    global _dup_names
    if not name:
        return name
    if _dup_names is None:
        _dup_names = _build_dup_names()
    peers = _dup_names.get(name)
    if not peers:
        return name
    try:
        import re
        from .multi_ops import _module_label
        module = operator_id.split(".", 1)[0]
        label = _module_label(operator_id)
        same_module = [p for p in peers
                       if p != operator_id and p.split(".", 1)[0] == module]
        if same_module:
            func = operator_id.split(".", 1)[1]
            name_toks = set(re.findall(r"[a-z]+", name.lower()))
            extra = [t for t in func.split("_")
                     if t and t not in name_toks and t != module]
            if extra:
                pretty = " ".join(_TOKEN_PRETTY.get(t, t.title())
                                  for t in extra)
                return f"{name} ({label} {pretty})"
        return f"{name} ({label})"
    except Exception:
        return name


def get_friendly_name(operator_id: str, qualify: bool = True) -> str | None:
    name = _raw_friendly(operator_id)
    if name and qualify:
        return qualify_op_label(operator_id, name)
    return name


def get_operator_source(operator_id: str) -> str:
    entry = FRIENDLY_NAMES.get(operator_id)
    return entry[1] if entry else "blender"


def is_bfa_only(operator_id: str) -> bool:
    return operator_id in BFA_ONLY_OPS


def get_filtered_names(host_app: str = "blender") -> dict:
    """Return friendly names dict filtered for the current host app."""
    if host_app == "bforartists":
        return {op: name for op, (name, _) in FRIENDLY_NAMES.items()}
    else:
        return {op: name for op, (name, src) in FRIENDLY_NAMES.items() if src == "blender"}
