"""Operator -> icon lookup for the simplified panel.

Two layers, checked in order:
  1. ``FULL_ID_ICONS``  — exact operator id (e.g. ``wm.call_menu_pie``)
  2. ``ACTION_ICONS``   — the action suffix after the dot (e.g. ``select_all``)

Most Blender operators share an action suffix across contexts
(``mesh.select_all``, ``object.select_all``, ``curve.select_all`` …), so
keying on the suffix means an entry that binds 30 ``*.select_all`` operators
collapses to a single icon. Anything unmatched falls back to ``FALLBACK_ICON``.

These are intentionally simple to edit — add or change entries freely. Icon
names are validated at draw time, so an unknown name degrades to the fallback
rather than crashing the panel.
"""

# Exact operator id wins over the action-suffix table.
FULL_ID_ICONS = {
    "keymapper.op_marking_menu": "MOD_DECIM",
    "keymapper.op_quick_view": "VIEWZOOM",
    "keymapper.op_select_tool_pie": "MOD_DECIM",
    "keymapper.op_pivot_transform": "PIVOT_CURSOR",
    "keymapper.op_open_assetbrowser_window": "ASSET_MANAGER",
    "wm.call_menu_pie": "MOD_DECIM",
    "wm.call_menu": "COLLAPSEMENU",
    "wm.call_panel": "MENU_PANEL",
    "wm.tool_set_by_id": "TOOL_SETTINGS",
    "wm.context_toggle": "CHECKBOX_HLT",
    "view3d.zoom_border": "ZOOM_SELECTED",
    "transform.translate": "ORIENTATION_GLOBAL",
    "transform.rotate": "DRIVER_ROTATIONAL_DIFFERENCE",
    "transform.resize": "FULLSCREEN_ENTER",
    "object.editmode_toggle": "EDITMODE_HLT",
    "object.add": "ADD",
}

# Action suffix (text after the first dot) -> icon. This is the main grouping
# key, so similar operators across contexts share one icon.
ACTION_ICONS = {
    "select_all": "RESTRICT_SELECT_OFF",
    "select_more": "ADD",
    "select_less": "REMOVE",
    "select_linked": "LINKED",
    "select_box": "SELECT_SET",
    "select_lasso": "MOD_DASH",
    "select_circle": "MESH_CIRCLE",
    "select_edge_loop": "EDGESEL",
    "select_edge_loop_multi": "EDGESEL",
    "select_mirror": "MOD_MIRROR",
    "select_similar": "LINKED",
    "select_grouped": "LINKED",
    "select_hierarchy": "OUTLINER_OB_EMPTY",
    "shortest_path_pick": "CURVE_PATH",
    "view_pan": "ARROW_LEFTRIGHT",
    "view_all": "FULLSCREEN_ENTER",
    "view_selected": "ZOOM_SELECTED",
    "view_frame": "TIME",
    "view_zoom": "VIEWZOOM",
    "view_zoom_in": "ZOOM_IN",
    "view_zoom_out": "ZOOM_OUT",
    "rotate": "FILE_REFRESH",
    "move": "VIEW_PAN",
    "zoom": "VIEWZOOM",
    "zoom_in": "ZOOM_IN",
    "zoom_out": "ZOOM_OUT",
    "translate": "ORIENTATION_GLOBAL",
    "resize": "FULLSCREEN_ENTER",
    "extrude_region": "MESH_DATA",
    "extrude_move": "MESH_DATA",
    "extrude": "MESH_DATA",
    "duplicate_move": "DUPLICATE",
    "duplicate_move_linked": "DUPLICATE",
    "fill": "FACE_MAPS",
    "split": "MOD_EXPLODE",
    "separate": "UNLINKED",
    "join": "OBJECT_DATA",
    "hide": "HIDE_ON",
    "reveal": "HIDE_OFF",
    "handle_type_set": "CURVE_BEZCURVE",
    "keyframe_insert": "KEYFRAME_HLT",
    "keyframe_delete": "KEYFRAME",
    "previewrange_set": "PREVIEW_RANGE",
    "face_edit": "FACESEL",
    "toggle_wireframe": "MOD_WIREFRAME",
    "editmode_toggle": "EDITMODE_HLT",
    "add": "ADD",
    "delete": "TRASH",
    "duplicate": "DUPLICATE",
    "toggle": "CHECKBOX_HLT",
    "parent_set": "PIVOT_ACTIVE",
    "parent_clear": "X",
}

FALLBACK_ICON = "DOT"

# BForArtists-only icons (not valid in standard Blender). Keyed by exact op id.
BFA_FULL_ID_ICONS = {
    "ed.undo": "UNDO",
    "ed.redo": "REDO",
    "screen.repeat_last": "REPEAT",
    "wm.search_menu": "ZOOM_SET",
}

FULL_ID_ICONS.update({
    "ed.undo": "LOOP_BACK",
    "ed.redo": "LOOP_FORWARDS",
    "wm.open_mainfile": "FILE_FOLDER",
    "wm.save_mainfile": "FILE_TICK",
    "screen.repeat_last": "CON_ROTLIKE",
    "wm.search_menu": "VIEWZOOM",
    "view2d.scroll_up": "TRIA_UP_BAR",
    "view2d.scroll_down": "TRIA_DOWN_BAR",
    "view2d.scroll_right": "TRIA_RIGHT_BAR",
    "view2d.scroll_left": "TRIA_LEFT_BAR",
    "view2d.pan": "ARROW_LEFTRIGHT",
    "view2d.zoom": "VIEWZOOM",
    "view2d.zoom_in": "ZOOM_IN",
    "view2d.zoom_out": "ZOOM_OUT",
    "wm.context_toggle": "MENU_PANEL",
    "wm.call_menu_pie": "CURVE_NCIRCLE",
    "wm.call_menu": "KEY_MENU",
    "view3d.localview": "VIS_SEL_11",
    "keymapper.op_marking_menu": "CURVE_NCIRCLE",
    "keymapper.op_quick_view": "CURVE_NCIRCLE",
    "keymapper.op_select_tool_pie": "CURVE_NCIRCLE",
    # Animation / timeline
    "screen.animation_play": "PLAY",
    "anim.keyframe_insert": "KEYFRAME_HLT",
    "anim.keyframe_delete": "KEYFRAME",
    "anim.channels_delete": "X",
    "anim.channels_select_all": "RESTRICT_SELECT_OFF",
    "anim.channels_view_selected": "ZOOM_SELECTED",
    "anim.previewrange_set": "PREVIEW_RANGE",
    "action.keyframe_insert": "KEYFRAME_HLT",
    "action.duplicate_move": "DUPLICATE",
    "action.previewrange_set": "PREVIEW_RANGE",
    "action.view_frame": "TIME",
    "graph.keyframe_insert": "KEYFRAME_HLT",
    "graph.duplicate_move": "DUPLICATE",
    "graph.previewrange_set": "PREVIEW_RANGE",
    "graph.view_frame": "TIME",
    "nla.duplicate_move": "DUPLICATE",
    "nla.previewrange_set": "PREVIEW_RANGE",
    "nla.view_frame": "TIME",
    "nla.split": "MOD_EXPLODE",
    # Clip / image / sequencer
    "clip.view_zoom": "VIEWZOOM",
    "clip.view_zoom_in": "ZOOM_IN",
    "clip.view_zoom_out": "ZOOM_OUT",
    "clip.keyframe_insert": "KEYFRAME_HLT",
    "clip.dopesheet_view_all": "FULLSCREEN_ENTER",
    "clip.graph_select_all": "RESTRICT_SELECT_OFF",
    "clip.graph_select_all_markers": "RESTRICT_SELECT_OFF",
    "clip.graph_view_all": "FULLSCREEN_ENTER",
    "image.view_zoom": "VIEWZOOM",
    "image.view_zoom_in": "ZOOM_IN",
    "image.view_zoom_out": "ZOOM_OUT",
    "sequencer.duplicate_move": "SEQ_STRIP_DUPLICATE",
    "sequencer.duplicate_move_linked": "SEQ_STRIP_DUPLICATE",
    "sequencer.split": "MOD_EXPLODE",
    "sequencer.select_grouped": "LINKED",
    "sequencer.text_select_all": "RESTRICT_SELECT_OFF",
    "sequencer.view_all_preview": "FULLSCREEN_ENTER",
    "sequencer.view_frame": "TIME",
    "sequencer.strip_modifier_add": "SEQ_STRIP_MODIFIER",
    "sequencer.strip_modifier_remove": "SEQ_STRIP_MODIFIER",
    "sequencer.strip_modifier_copy": "SEQ_STRIP_MODIFIER",
    "sequencer.strip_modifier_move": "SEQ_STRIP_MODIFIER",
    # Mesh / edit
    "mesh.duplicate_move": "DUPLICATE",
    "mesh.fill": "FACE_MAPS",
    "mesh.select_mirror": "MOD_MIRROR",
    "mesh.select_similar": "LINKED",
    "mesh.separate": "UNLINKED",
    "mesh.shortest_path_pick": "CURVE_PATH",
    "mesh.split": "MOD_EXPLODE",
    "view3d.edit_mesh_extrude_move_normal": "NORMALS_FACE",
    # Curve / curves
    "curve.duplicate_move": "DUPLICATE",
    "curve.extrude_move": "MESH_DATA",
    "curve.handle_type_set": "CURVE_BEZCURVE",
    "curve.select_similar": "LINKED",
    "curve.separate": "UNLINKED",
    "curve.shortest_path_pick": "CURVE_PATH",
    "curve.split": "MOD_EXPLODE",
    "curves.duplicate_move": "DUPLICATE",
    "curves.extrude_move": "MESH_DATA",
    "curves.handle_type_set": "CURVE_BEZCURVE",
    "curves.separate": "UNLINKED",
    "curves.split": "MOD_EXPLODE",
    # Armature / pose
    "armature.duplicate_move": "DUPLICATE",
    "armature.extrude_move": "MESH_DATA",
    "armature.fill": "FACE_MAPS",
    "armature.parent_clear": "X",
    "armature.parent_set": "BONE_DATA",
    "armature.select_hierarchy": "OUTLINER_OB_ARMATURE",
    "armature.select_mirror": "MOD_MIRROR",
    "armature.select_similar": "LINKED",
    "armature.separate": "UNLINKED",
    "armature.shortest_path_pick": "CURVE_PATH",
    "armature.split": "MOD_EXPLODE",
    "pose.select_grouped": "LINKED",
    "pose.select_hierarchy": "OUTLINER_OB_ARMATURE",
    "pose.select_mirror": "MOD_MIRROR",
    # Object
    "object.duplicate_move": "DUPLICATE",
    "object.duplicate_move_linked": "DUPLICATE",
    "object.join": "OBJECT_DATA",
    "object.move_to_collection": "OUTLINER_COLLECTION",
    "object.parent_clear": "X",
    "object.parent_set": "PIVOT_ACTIVE",
    "object.select_grouped": "LINKED",
    "object.select_hierarchy": "OUTLINER_OB_EMPTY",
    "object.select_mirror": "MOD_MIRROR",
    # Grease pencil / annotation
    "gpencil.annotation_active_frame_delete": "TRASH",
    "grease_pencil.delete_frame": "TRASH",
    "grease_pencil.duplicate_move": "DUPLICATE",
    "grease_pencil.extrude_move": "MESH_DATA",
    "grease_pencil.fill": "FACE_MAPS",
    "grease_pencil.select_similar": "LINKED",
    "grease_pencil.separate": "UNLINKED",
    "grease_pencil.split": "MOD_EXPLODE",
    # Mask / mball / node / particle / pointcloud / uv
    "mask.duplicate_move": "DUPLICATE",
    "mask.handle_type_set": "CURVE_BEZCURVE",
    "mask.parent_clear": "X",
    "mask.parent_set": "PIVOT_ACTIVE",
    "mball.duplicate_move": "DUPLICATE",
    "mball.select_similar": "LINKED",
    "node.duplicate_move": "DUPLICATE",
    "node.duplicate_move_linked": "DUPLICATE",
    "node.join": "NODE",
    "node.parent_set": "PIVOT_ACTIVE",
    "node.select_grouped": "LINKED",
    "particle.reveal": "HIDE_OFF",
    "pointcloud.duplicate_move": "DUPLICATE",
    "pointcloud.separate": "UNLINKED",
    "uv.select_similar": "LINKED",
    "uv.shortest_path_pick": "CURVE_PATH",
    # Paint
    "paint.face_select_all": "RESTRICT_SELECT_OFF",
    "paint.face_select_less": "REMOVE",
    "paint.face_select_more": "ADD",
    "paint.vert_select_all": "RESTRICT_SELECT_OFF",
    "paint.vert_select_less": "REMOVE",
    "paint.vert_select_more": "ADD",
    # Outliner / sequencer
    "outliner.hide": "HIDE_ON",
    # NLA channel
    "anim.channels_view_selected": "ZOOM_SELECTED",
})

# Ops in the Hide/Reveal presets that don't end in _hide/_reveal but belong
# to those concepts.
_HIDE_EXTRA = {
    "grease_pencil.layer_hide", "mask.hide_view_set", "mball.hide_metaelems",
    "node.hide_toggle", "object.hide_view_set",
}
_REVEAL_EXTRA = {
    "grease_pencil.layer_reveal", "mask.hide_view_clear",
    "mball.reveal_metaelems", "object.hide_view_clear", "outliner.unhide_all",
}


_VALID_ICON_NAMES = None


def _icon_or_fallback(name: str, pre52_fallback: str = FALLBACK_ICON) -> str:
    """Return `name` if it exists in this Blender build, else a fallback.

    Some mapped icons (e.g. the 5.2 SEQ_STRIP* set) don't exist on 5.1. Callers
    that pass get_op_icon's result straight to layout.operator(icon=...) would
    crash on those builds, so we degrade here at the single source. When a
    specific `pre52_fallback` is given (a pre-5.2 icon that DOES exist), we use
    it instead of the generic DOT so older builds keep a meaningful icon.
    """
    global _VALID_ICON_NAMES
    if _VALID_ICON_NAMES is None:
        try:
            import bpy
            enum = (bpy.types.UILayout.bl_rna.functions["operator"]
                    .parameters["icon"].enum_items)
            _VALID_ICON_NAMES = {item.identifier for item in enum}
        except Exception:
            _VALID_ICON_NAMES = set()
    if not _VALID_ICON_NAMES:
        return name  # introspection unavailable — trust the name
    if name in _VALID_ICON_NAMES:
        return name
    if pre52_fallback in _VALID_ICON_NAMES:
        return pre52_fallback
    return FALLBACK_ICON


# Icons that only exist on Blender 5.2+, mapped to a pre-5.2 equivalent so older
# builds still show something meaningful instead of a blank DOT.
_NEW_ICON_FALLBACKS = {
    "SEQ_STRIP_DUPLICATE": "DUPLICATE",
    "SEQ_STRIP_MODIFIER": "MODIFIER",
    "SEQ_STRIP_DATA": "SEQ_SEQUENCER",
    "SEQ_STRIP": "SEQ_SEQUENCER",
}


def get_op_icon(op_id: str) -> str:
    """Return an icon name for ``op_id`` (BFA override, full-id, patterns, action)."""
    raw = _get_op_icon_raw(op_id)
    return _icon_or_fallback(raw, _NEW_ICON_FALLBACKS.get(raw, FALLBACK_ICON))


def _get_op_icon_raw(op_id: str) -> str:
    """Resolve the mapped icon name without version validation."""
    if not op_id:
        return FALLBACK_ICON

    try:
        from .. import HOST_APP
        is_bfa = HOST_APP == "bforartists"
    except Exception:
        is_bfa = False

    if is_bfa and op_id in BFA_FULL_ID_ICONS:
        return BFA_FULL_ID_ICONS[op_id]
    if op_id in FULL_ID_ICONS:
        return FULL_ID_ICONS[op_id]

    # Pattern rules
    if "rename" in op_id:
        return "RENAME" if is_bfa else "FILE_TEXT"
    if "select_linked_pick" in op_id or "select_linked" in op_id:
        return "LINKED"
    if op_id.endswith("_pan"):
        return "VIEW_PAN"
    # Plain click-select variants across editors
    _func = op_id.split(".", 1)[1] if "." in op_id else op_id
    if _func in ("select", "clickselect", "click_select", "select_pick",
                 "select_set", "dopesheet_select_channel"):
        return "RESTRICT_SELECT_OFF"
    # Eyedropper pickers
    if "eyedropper" in op_id:
        return "EYEDROPPER"
    # Extrude family (mesh/curve/armature + view3d edit_mesh_extrude wrappers)
    if "extrude" in op_id:
        return "FACESEL"
    # Filter / find fields
    if _func in ("start_filter", "list_start_filter", "view_start_filter",
                 "clear_filter", "start_find"):
        return "FILTER"
    if op_id.endswith("_hide") or op_id in _HIDE_EXTRA:
        return "HIDE_ON"
    if op_id.endswith("_reveal") or op_id in _REVEAL_EXTRA:
        return "HIDE_OFF"

    action = op_id.split(".", 1)[1] if "." in op_id else op_id
    return ACTION_ICONS.get(action, FALLBACK_ICON)

# ---------------------------------------------------------------------------
# Broad action-suffix coverage for the full operator list
ACTION_ICONS.update({
    # Frame / time
    "change_frame": "TIME",
    "frame_jump": "NEXT_KEYFRAME",
    "keyframe_jump": "NEXT_KEYFRAME",
    "view_frame": "TIME",
    "previewrange_clear": "PREVIEW_RANGE",
    "start_frame_set": "TRIA_RIGHT",
    "end_frame_set": "TRIA_LEFT",
    "scene_range_frame": "PREVIEW_RANGE",
    # Keyframes (clear / extra variants)
    "keyframe_clear_button": "KEYFRAME",
    "keyframe_clear_v3d": "KEYFRAME",
    "keyframe_clear_vse": "KEYFRAME",
    "keyframe_delete_button": "KEYFRAME",
    "keyframe_delete_v3d": "KEYFRAME",
    "keyframe_delete_vse": "KEYFRAME",
    "keyframe_insert_button": "KEYFRAME_HLT",
    "keyframe_insert_by_name": "KEYFRAME_HLT",
    "keyframe_insert_menu": "KEYFRAME_HLT",
    "keyframe_delete_by_name": "KEYFRAME",
    # Channels
    "channels_rename": "FONT_DATA",
    "channels_collapse": "TRIA_RIGHT",
    "channels_expand": "TRIA_DOWN",
    "channels_move": "SORTALPHA",
    "channels_click": "MOUSE_LMB",
    "channels_select_box": "SELECT_SET",
    "channels_select_filter": "FILTER",
    "channels_group": "GROUP",
    "channels_ungroup": "UNLINKED",
    "channels_editable_toggle": "LOCKED",
    "channels_fcurves_enable": "FCURVE",
    "channels_setting_enable": "CHECKBOX_HLT",
    "channels_setting_disable": "CHECKBOX_DEHLT",
    "channels_setting_toggle": "CHECKBOX_HLT",
    "channels_bake": "RENDER_ANIMATION",
    "channels_clean_empty": "TRASH",
    "channel_select_keys": "KEYFRAME_HLT",
    "channel_view_pick": "ZOOM_SELECTED",
    # Drivers / keying sets
    "driver_button_add": "DRIVER",
    "driver_button_edit": "DRIVER",
    "driver_button_remove": "DRIVER",
    "copy_driver_button": "DRIVER",
    "paste_driver_button": "DRIVER",
    "keying_set_add": "KEYINGSET",
    "keying_set_remove": "KEYINGSET",
    "keying_set_export": "EXPORT",
    "keying_set_path_add": "KEYINGSET",
    "keying_set_path_remove": "KEYINGSET",
    "keying_set_active_set": "KEYINGSET",
    "keyingset_button_add": "KEYINGSET",
    "keyingset_button_remove": "KEYINGSET",
    "keyframe_insert_menu": "KEYFRAME_HLT",
    # Animation misc
    "clear_useless_actions": "TRASH",
    "merge_animation": "NLA",
    "separate_slots": "UNLINKED",
    "view_curve_in_graph_editor": "GRAPH",
    "bake_keys": "RENDER_ANIMATION",
    # Select helpers
    "select_leftright": "ARROW_LEFTRIGHT",
    "select_column": "SNAP_INCREMENT",
    "select_ends": "CURVE_PATH",
    "select_random": "RNDCURVE",
    "select_nth": "PARTICLE_POINT",
    "select_ungrouped": "UNLINKED",
    "select_axis": "ORIENTATION_GLOBAL",
    "select_mode": "RESTRICT_SELECT_OFF",
    "select_next_item": "TRIA_RIGHT",
    "select_prev_item": "TRIA_LEFT",
    "select_non_manifold": "SELECT_INTERSECT",
    "select_interior_faces": "FACESEL",
    "select_loose": "UNLINKED",
    "select_face_by_sides": "FACESEL",
    "select_by_attribute": "SPREADSHEET",
    "select_by_pole_count": "VERTEXSEL",
    "select_similar_region": "LINKED",
    "select_alternate": "PARTICLE_POINT",
    "select_fill": "FACE_MAPS",
    "select_by_stroke_type": "STROKE",
    # Edit ops
    "dissolve_verts": "REMOVE",
    "dissolve_edges": "REMOVE",
    "dissolve_faces": "REMOVE",
    "dissolve_limited": "REMOVE",
    "dissolve_degenerate": "REMOVE",
    "dissolve_mode": "REMOVE",
    "merge": "AUTOMERGE_ON",
    "merge_normals": "NORMALS_VERTEX",
    "bevel": "MOD_BEVEL",
    "subdivide": "MOD_SUBSURF",
    "subdivide_edgering": "MOD_SUBSURF",
    "unsubdivide": "MOD_SUBSURF",
    "inset": "MESH_DATA",
    "poke": "MESH_DATA",
    "spin": "MESH_DATA",
    "screw": "MOD_SCREW",
    "solidify": "MOD_SOLIDIFY",
    "wireframe": "MOD_WIREFRAME",
    "bisect": "MOD_BOOLEAN",
    "intersect": "MOD_BOOLEAN",
    "intersect_boolean": "MOD_BOOLEAN",
    "convex_hull": "MESH_ICOSPHERE",
    "decimate": "MOD_DECIM",
    "bridge_edge_loops": "EDGESEL",
    "loopcut": "EDGESEL",
    "loopcut_slide": "EDGESEL",
    "loop_select": "EDGESEL",
    "edgering_select": "EDGESEL",
    "loop_to_region": "FACESEL",
    "region_to_loop": "EDGESEL",
    "edge_split": "MOD_EDGESPLIT",
    "edge_rotate": "FILE_REFRESH",
    "edge_collapse": "REMOVE",
    "edge_face_add": "FACE_MAPS",
    "offset_edge_loops": "EDGESEL",
    "offset_edge_loops_slide": "EDGESEL",
    "rip": "UNLINKED",
    "rip_move": "UNLINKED",
    "rip_edge": "UNLINKED",
    "rip_edge_move": "UNLINKED",
    "vert_connect": "VERTEXSEL",
    "vert_connect_path": "CURVE_PATH",
    "vert_connect_concave": "VERTEXSEL",
    "vert_connect_nonplanar": "VERTEXSEL",
    "vertices_smooth": "MOD_SMOOTH",
    "vertices_smooth_laplacian": "MOD_SMOOTH",
    "smooth_normals": "NORMALS_VERTEX",
    "normals_make_consistent": "NORMALS_FACE",
    "normals_tools": "NORMALS_FACE",
    "average_normals": "NORMALS_FACE",
    "set_normals_from_faces": "NORMALS_FACE",
    "point_normals": "NORMALS_VERTEX",
    "blend_from_shape": "SHAPEKEY_DATA",
    "shape_propagate_to_all": "SHAPEKEY_DATA",
    "beautify_fill": "FACE_MAPS",
    "fill_grid": "FACE_MAPS",
    "fill_holes": "FACE_MAPS",
    "flip_normals": "NORMALS_FACE",
    "flip_quad_tessellation": "MESH_DATA",
    "tris_convert_to_quads": "MESH_DATA",
    "quads_convert_to_tris": "MESH_DATA",
    "remove_doubles": "AUTOMERGE_ON",
    "mark_seam": "UV_DATA",
    "mark_sharp": "EDGESEL",
    "mark_freestyle_edge": "LINE_DATA",
    "mark_freestyle_face": "LINE_DATA",
    "faces_select_linked_flat": "FACESEL",
    "edges_select_sharp": "EDGESEL",
    "face_make_planar": "FACESEL",
    "face_split_by_edges": "FACESEL",
    "knife_tool": "MOD_DECIM",
    "knife_project": "MOD_DECIM",
    "dupli_extrude_cursor": "CURSOR",
    "sort_elements": "SORTSIZE",
    "reorder_vertices_spatial": "SORTSIZE",
    "customdata_custom_splitnormals_add": "NORMALS_VERTEX",
    "customdata_custom_splitnormals_clear": "NORMALS_VERTEX",
    "customdata_skin_add": "MOD_SKIN",
    "customdata_skin_clear": "MOD_SKIN",
    "customdata_mask_clear": "MOD_MASK",
    "uv_texture_add": "UV_DATA",
    "uv_texture_remove": "UV_DATA",
    "uvs_rotate": "UV_DATA",
    "uvs_reverse": "UV_DATA",
    "colors_rotate": "COLOR",
    "colors_reverse": "COLOR",
    "set_sharpness_by_angle": "EDGESEL",
    # Primitives
    "primitive_plane_add": "MESH_PLANE",
    "primitive_cube_add": "MESH_CUBE",
    "primitive_cube_add_gizmo": "MESH_CUBE",
    "primitive_circle_add": "MESH_CIRCLE",
    "primitive_cylinder_add": "MESH_CYLINDER",
    "primitive_cone_add": "MESH_CONE",
    "primitive_grid_add": "MESH_GRID",
    "primitive_uv_sphere_add": "MESH_UVSPHERE",
    "primitive_ico_sphere_add": "MESH_ICOSPHERE",
    "primitive_torus_add": "MESH_TORUS",
    "primitive_monkey_add": "MESH_MONKEY",
    "primitive_bezier_curve_add": "CURVE_BEZCURVE",
    "primitive_bezier_circle_add": "CURVE_BEZCIRCLE",
    "primitive_nurbs_curve_add": "CURVE_NCURVE",
    "primitive_nurbs_circle_add": "CURVE_NCIRCLE",
    "primitive_nurbs_path_add": "CURVE_PATH",
    # Transforms
    "shrink_fatten": "NORMALS_FACE",
    "push_pull": "FULLSCREEN_ENTER",
    "bend": "MOD_SIMPLEDEFORM",
    "shear": "MOD_SIMPLEDEFORM",
    "tosphere": "MESH_UVSPHERE",
    "trackball": "FILE_REFRESH",
    "edge_slide": "EDGESEL",
    "vert_slide": "VERTEXSEL",
    "seq_slide": "NLA_PUSHDOWN",
    "tilt": "CURVE_DATA",
    "skin_resize": "MOD_SKIN",
    "bbone_resize": "BONE_DATA",
    "rotate_normal": "NORMALS_FACE",
    "create_orientation": "ORIENTATION_LOCAL",
    "delete_orientation": "ORIENTATION_LOCAL",
    "select_orientation": "ORIENTATION_LOCAL",
    "from_gizmo": "GIZMO",
    "edge_crease": "EDGESEL",
    "edge_bevelweight": "MOD_BEVEL",
    "vert_crease": "VERTEXSEL",
    "vertex_random": "RNDCURVE",
    "vertex_warp": "MOD_WARP",
    "mirror": "MOD_MIRROR",
    "symmetrize": "MOD_MIRROR",
    "symmetry_snap": "MOD_MIRROR",
    "switch_direction": "ARROW_LEFTRIGHT",
    "cyclic_toggle": "LOOP_BACK",
    "tilt_clear": "CURVE_DATA",
    "radius_set": "CURVE_DATA",
    "spline_type_set": "CURVE_DATA",
    "spline_weight_set": "CURVE_DATA",
    "smooth": "MOD_SMOOTH",
    "smooth_radius": "MOD_SMOOTH",
    "smooth_tilt": "MOD_SMOOTH",
    "smooth_weight": "MOD_SMOOTH",
    # Curve / Grease pencil draw
    "draw": "GREASEPENCIL",
    "pen": "GREASEPENCIL",
    "make_segment": "EDGESEL",
    "select_row": "RESTRICT_SELECT_OFF",
    "select_next": "TRIA_RIGHT",
    "select_previous": "TRIA_LEFT",
    "shade_flat": "MESH_DATA",
    "shade_smooth": "MESH_DATA",
    "decimate": "MOD_DECIM",
    # Armature
    "bone_primitive_add": "BONE_DATA",
    "subdivide": "MOD_SUBSURF",
    "dissolve": "REMOVE",
    "extrude_forked": "MESH_DATA",
    "fill": "FACE_MAPS",
    "roll_clear": "BONE_DATA",
    "flip_names": "FONT_DATA",
    "autoside_names": "FONT_DATA",
    "calculate_roll": "BONE_DATA",
    "click_extrude": "MESH_DATA",
    "align": "ALIGN_CENTER",
    "collection_add": "OUTLINER_COLLECTION",
    "collection_remove": "OUTLINER_COLLECTION",
    "collection_assign": "OUTLINER_COLLECTION",
    "collection_select": "OUTLINER_COLLECTION",
    "collection_deselect": "OUTLINER_COLLECTION",
    "collection_move": "OUTLINER_COLLECTION",
    "collection_show_all": "OUTLINER_COLLECTION",
    "collection_unassign": "OUTLINER_COLLECTION",
    "copy_bone_color_to_selected": "COLOR",
    "assign_to_collection": "OUTLINER_COLLECTION",
    "move_to_collection": "OUTLINER_COLLECTION",
    # Pose
    "breakdown": "KEYFRAME_HLT",
    "push": "KEYFRAME_HLT",
    "relax": "KEYFRAME_HLT",
    "blend_with_rest": "POSE_HLT",
    "blend_to_neighbor": "POSE_HLT",
    "propagate": "POSE_HLT",
    "copy": "COPYDOWN",
    "paste": "PASTEDOWN",
    "loc_clear": "OBJECT_ORIGIN",
    "rot_clear": "OBJECT_ORIGIN",
    "scale_clear": "OBJECT_ORIGIN",
    "location_clear": "OBJECT_ORIGIN",
    "rotation_clear": "OBJECT_ORIGIN",
    "transforms_clear": "OBJECT_ORIGIN",
    "ik_add": "CON_KINEMATIC",
    "ik_clear": "CON_KINEMATIC",
    "constraint_add": "CONSTRAINT_BONE",
    "constraints_clear": "CONSTRAINT_BONE",
    "constraints_copy": "CONSTRAINT_BONE",
    "quaternions_flip": "DRIVER_ROTATIONAL_DIFFERENCE",
    "rotation_mode_set": "DRIVER_ROTATIONAL_DIFFERENCE",
    "armature_apply": "ARMATURE_DATA",
    "visual_transform_apply": "OBJECT_DATA",
    "transform_apply": "OBJECT_DATA",
    "paths_calculate": "CURVE_PATH",
    "paths_clear": "CURVE_PATH",
    "paths_update": "CURVE_PATH",
    # Sculpt
    "sculptmode_toggle": "SCULPTMODE_HLT",
    "paintmode_toggle": "GREASEPENCIL",
    "vertexmode_toggle": "MESH_DATA",
    "weightmode_toggle": "MOD_VERTEX_WEIGHT",
    "brush_stroke": "BRUSH_DATA",
    "cloth_filter": "MOD_CLOTH",
    "color_filter": "COLOR",
    "mask_filter": "MOD_MASK",
    "mesh_filter": "MESH_DATA",
    "mask_by_color": "MOD_MASK",
    "mask_from_cavity": "MOD_MASK",
    "mask_from_boundary": "MOD_MASK",
    "mask_init": "MOD_MASK",
    "paint_mask_extract": "MOD_MASK",
    "paint_mask_slice": "MOD_MASK",
    "face_set_edit": "FACE_MAPS",
    "face_set_extract": "FACE_MAPS",
    "face_set_change_visibility": "FACE_MAPS",
    "face_sets_create": "FACE_MAPS",
    "face_sets_init": "FACE_MAPS",
    "face_sets_randomize_colors": "FACE_MAPS",
    "detail_flood_fill": "MESH_DATA",
    "dynamic_topology_toggle": "MESH_DATA",
    "dyntopo_detail_size_edit": "MESH_DATA",
    "optimize": "FILE_REFRESH",
    "set_pivot_position": "PIVOT_CURSOR",
    "set_persistent_base": "MESH_DATA",
    "sample_detail_size": "MESH_DATA",
    "expand": "FULLSCREEN_ENTER",
    "trim_box_gesture": "SELECT_SET",
    "trim_lasso_gesture": "MOD_DASH",
    # Paint
    "image_paint": "TPAINT_HLT",
    "texture_paint_toggle": "TPAINT_HLT",
    "vertex_paint": "VPAINT_HLT",
    "vertex_paint_toggle": "VPAINT_HLT",
    "weight_paint": "WPAINT_HLT",
    "weight_paint_toggle": "WPAINT_HLT",
    "vertex_color_set": "COLOR",
    "vertex_color_smooth": "MOD_SMOOTH",
    "vertex_color_dirt": "MOD_SMOOTH",
    "vertex_color_from_weight": "MOD_VERTEX_WEIGHT",
    "vertex_color_invert": "IMAGE_ALPHA",
    "vertex_color_levels": "GHOST_ENABLED",
    "vertex_color_brightness_contrast": "GHOST_ENABLED",
    "vertex_color_hsv": "COLOR",
    "weight_from_bones": "BONE_DATA",
    "weight_set": "MOD_VERTEX_WEIGHT",
    "weight_gradient": "WPAINT_HLT",
    "weight_sample": "EYEDROPPER",
    "weight_sample_group": "EYEDROPPER",
    "sample_color": "EYEDROPPER",
    "grab_clone": "HAND",
    "face_select_loop": "EDGESEL",
    "mask_flood_fill": "MOD_MASK",
    "mask_box_gesture": "SELECT_SET",
    "mask_lasso_gesture": "MOD_DASH",
    "hide_show": "HIDE_ON",
    "hide_show_all": "HIDE_OFF",
    "brush_colors_flip": "ARROW_LEFTRIGHT",
    # Particle
    "particle_edit_toggle": "PARTICLES",
    "brush_edit": "PARTICLES",
    "connect_hair": "PARTICLES",
    "disconnect_hair": "PARTICLES",
    "shape_cut": "MOD_DECIM",
    "rekey": "KEYFRAME_HLT",
    "unify_length": "PARTICLES",
    "select_roots": "PARTICLES",
    "select_tips": "PARTICLES",
    # Grease pencil
    "interpolate": "IPO_BEZIER",
    "interpolate_sequence": "IPO_BEZIER",
    "stroke_smooth": "MOD_SMOOTH",
    "stroke_simplify": "MOD_DECIM",
    "stroke_subdivide": "MOD_SUBSURF",
    "stroke_subdivide_smooth": "MOD_SUBSURF",
    "stroke_merge_by_distance": "AUTOMERGE_ON",
    "stroke_trim": "UNLINKED",
    "stroke_split": "MOD_EXPLODE",
    "stroke_switch_direction": "ARROW_LEFTRIGHT",
    "stroke_material_set": "MATERIAL",
    "stroke_reset_vertex_color": "COLOR",
    "layer_add": "ADD",
    "layer_remove": "REMOVE",
    "layer_move": "SORTALPHA",
    "layer_duplicate": "DUPLICATE",
    "layer_merge": "OBJECT_DATA",
    "layer_isolate": "RESTRICT_VIEW_OFF",
    "layer_lock_all": "LOCKED",
    "layer_group_add": "GROUP",
    "layer_group_remove": "GROUP",
    "material_hide": "HIDE_ON",
    "material_reveal": "HIDE_OFF",
    "material_isolate": "RESTRICT_VIEW_OFF",
    "material_lock_all": "LOCKED",
    "material_unlock_all": "UNLOCKED",
    "material_lock_unselected": "LOCKED",
    "material_lock_unused": "LOCKED",
    "material_select": "MATERIAL",
    "material_copy_to_object": "MATERIAL",
    "move_to_layer": "SORTALPHA",
    "insert_blank_frame": "BLANK1",
    "frame_duplicate": "DUPLICATE",
    "delete_frame": "TRASH",
    "active_frame_delete": "TRASH",
    "trace_image": "IMAGE_DATA",
    "set_selection_mode": "RESTRICT_SELECT_OFF",
    "set_stroke_type": "STROKE",
    "set_corner_type": "CURVE_DATA",
    "set_handle_type": "CURVE_BEZCURVE",
    "set_curve_type": "CURVE_DATA",
    "snap_cursor_to_selected": "CURSOR",
    "snap_to_cursor": "CURSOR",
    "snap_to_grid": "SNAP_GRID",
    "primitive_line": "MESH_PLANE",
    "primitive_arc": "CURVE_BEZCURVE",
    "primitive_box": "MESH_CUBE",
    "primitive_circle": "CURVE_BEZCIRCLE",
    "primitive_polyline": "CURVE_PATH",
    "primitive_curve": "CURVE_BEZCURVE",
    # Node
    "add_node": "ADD",
    "add_group": "NODETREE",
    "add_reroute": "NODE",
    "group_make": "NODETREE",
    "group_ungroup": "NODETREE",
    "group_edit": "NODETREE",
    "group_enter_exit": "NODETREE",
    "link_make": "LINKED",
    "links_cut": "UNLINKED",
    "links_detach": "UNLINKED",
    "links_mute": "RESTRICT_VIEW_ON",
    "mute_toggle": "RESTRICT_VIEW_ON",
    "hide_toggle": "HIDE_ON",
    "hide_socket_toggle": "HIDE_ON",
    "collapse_hide_unused_toggle": "HIDE_ON",
    "preview_toggle": "RESTRICT_VIEW_OFF",
    "activate_viewer": "HIDE_OFF",
    "connect_to_output": "NODE",
    "tree_path_parent": "FILE_PARENT",
    "find_node": "VIEWZOOM",
    "detach": "UNLINKED",
    "attach": "LINKED",
    "insert_offset": "NODE",
    "translate_attach": "LINKED",
    "swap_node": "NODE",
    "options_toggle": "PREFERENCES",
    "select_link_viewer": "RESTRICT_VIEW_OFF",
    "select_linked_from": "LINKED",
    "select_linked_to": "LINKED",
    "select_same_type_step": "LINKED",
    # UV
    "unwrap": "UV_DATA",
    "smart_project": "UV_DATA",
    "cube_project": "UV_DATA",
    "cylinder_project": "UV_DATA",
    "sphere_project": "UV_DATA",
    "project_from_view": "UV_DATA",
    "lightmap_pack": "UV_DATA",
    "pack_islands": "UV_DATA",
    "average_islands_scale": "UV_DATA",
    "arrange_islands": "UV_DATA",
    "minimize_stretch": "UV_DATA",
    "stitch": "UV_DATA",
    "weld": "AUTOMERGE_ON",
    "pin": "PINNED",
    "mark_seam": "UV_DATA",
    "seams_from_islands": "UV_DATA",
    "reset": "LOOP_BACK",
    "follow_active_quads": "FACESEL",
    "select_pinned": "PINNED",
    "select_overlap": "SELECT_INTERSECT",
    "select_split": "UNLINKED",
    "select_tile": "TEXTURE",
    "select_edge_ring": "EDGESEL",
    "select_loop": "EDGESEL",
    "align": "ALIGN_CENTER",
    "align_rotation": "DRIVER_ROTATIONAL_DIFFERENCE",
    "snap_cursor": "CURSOR",
    "snap_selected": "CURSOR",
    "copy_mirrored_faces": "MOD_MIRROR",
    "cursor_set": "CURSOR",
    "rip": "UNLINKED",
    "rip_move": "UNLINKED",
    "shortest_path_select": "CURVE_PATH",
    "select_mode": "RESTRICT_SELECT_OFF",
    "move_on_axis": "ORIENTATION_GLOBAL",
    # Sequencer
    "meta_make": "SEQ_SEQUENCER",
    "meta_separate": "SEQ_SEQUENCER",
    "meta_toggle": "SEQ_SEQUENCER",
    "slip": "SEQ_SEQUENCER",
    "snap": "SNAP_ON",
    "crossfade_sounds": "SEQ_SEQUENCER",
    "fades_add": "IPO_EASE_IN_OUT",
    "fades_clear": "IPO_EASE_IN_OUT",
    "gap_insert": "SEQ_SEQUENCER",
    "gap_remove": "SEQ_SEQUENCER",
    "rendersize": "RENDER_RESULT",
    "enable_proxies": "SEQ_SEQUENCER",
    "rebuild_proxy": "SEQ_SEQUENCER",
    "export_subtitles": "EXPORT",
    "effect_strip_add": "SEQ_SEQUENCER",
    "movie_strip_add": "FILE_MOVIE",
    "image_strip_add": "FILE_IMAGE",
    "sound_strip_add": "FILE_SOUND",
    "scene_strip_add": "SCENE_DATA",
    "mask_strip_add": "MOD_MASK",
    "lock": "LOCKED",
    "unlock": "UNLOCKED",
    "mute": "MUTE_IPO_ON",
    "unmute": "MUTE_IPO_OFF",
    "strip_jump": "NEXT_KEYFRAME",
    "strip_color_tag_set": "COLOR",
    "strip_transform_clear": "LOOP_BACK",
    "strip_transform_fit": "FULLSCREEN_ENTER",
    "strip_modifier_add": "ADD",
    "strip_modifier_copy": "DUPLICATE",
    "retiming_show": "TIME",
    "images_separate": "UNLINKED",
    "swap": "ARROW_LEFTRIGHT",
    "swap_data": "ARROW_LEFTRIGHT",
    "swap_inputs": "ARROW_LEFTRIGHT",
    "text_edit_mode_toggle": "SMALL_CAPS",
    "text_delete": "TRASH",
    "text_insert": "FONT_DATA",
    "text_line_break": "SMALL_CAPS",
    "text_edit_copy": "COPYDOWN",
    "text_edit_cut": "COPYDOWN",
    "text_edit_paste": "PASTEDOWN",
    "text_cursor_move": "CURSOR",
    "text_deselect_all": "RESTRICT_SELECT_OFF",
    "change_effect_type": "SEQ_SEQUENCER",
    "change_scene": "SCENE_DATA",
    "connect": "LINKED",
    "disconnect": "UNLINKED",
    "reassign_inputs": "LINKED",
    "refresh_all": "FILE_REFRESH",
    "set_range_to_strips": "PREVIEW_RANGE",
    # Object misc
    "origin_set": "OBJECT_ORIGIN",
    "origin_clear": "OBJECT_ORIGIN",
    "shade_flat": "MESH_DATA",
    "shade_smooth": "MESH_DATA",
    "shade_auto_smooth": "MESH_DATA",
    "convert": "OBJECT_DATA",
    "transform_to_mouse": "CURSOR",
    "make_local": "LINKED",
    "make_single_user": "UNLINKED",
    "make_links_data": "LINKED",
    "duplicates_make_real": "DUPLICATE",
    "mode_set": "OBJECT_DATA",
    "posemode_toggle": "POSE_HLT",
    "location_clear": "OBJECT_ORIGIN",
    "rotation_clear": "OBJECT_ORIGIN",
    "scale_clear": "OBJECT_ORIGIN",
    "randomize_transform": "RNDCURVE",
    "align": "ALIGN_CENTER",
    "visual_geometry_to_objects": "OBJECT_DATA",
    "link_to_collection": "OUTLINER_COLLECTION",
    "collection_link": "OUTLINER_COLLECTION",
    "modifier_add": "MODIFIER",
    "modifier_remove": "MODIFIER",
    "modifier_apply": "MODIFIER",
    "modifier_copy": "DUPLICATE",
    "modifier_move_up": "TRIA_UP",
    "modifier_move_down": "TRIA_DOWN",
    "vertex_group_add": "GROUP_VERTEX",
    "vertex_group_remove": "GROUP_VERTEX",
    "vertex_group_assign": "GROUP_VERTEX",
    "vertex_group_deselect": "GROUP_VERTEX",
    "vertex_group_select": "GROUP_VERTEX",
    "vertex_group_clean": "GROUP_VERTEX",
    "vertex_group_invert": "GROUP_VERTEX",
    "vertex_group_mirror": "GROUP_VERTEX",
    "vertex_group_smooth": "GROUP_VERTEX",
    "vertex_group_normalize": "GROUP_VERTEX",
    "vertex_group_normalize_all": "GROUP_VERTEX",
    "vertex_group_lock": "LOCKED",
    "vertex_group_sort": "GROUP_VERTEX",
    "vertex_group_copy": "DUPLICATE",
    "vertex_group_move": "SORTALPHA",
    "vertex_weight_set_active": "GROUP_VERTEX",
    "vertex_weight_paste": "PASTEDOWN",
    "shape_key_add": "SHAPEKEY_DATA",
    "shape_key_remove": "SHAPEKEY_DATA",
    "shape_key_clear": "SHAPEKEY_DATA",
    "shape_key_copy": "DUPLICATE",
    "shape_key_move": "SORTALPHA",
    "shape_key_mirror": "MOD_MIRROR",
    "shape_key_lock": "LOCKED",
    # View3d navigation
    "view_orbit": "FILE_REFRESH",
    "view_roll": "FILE_REFRESH",
    "view_axis": "ORIENTATION_VIEW",
    "view_camera": "CAMERA_DATA",
    "view_persportho": "VIEW_PERSPECTIVE",
    "view_center_cursor": "CURSOR",
    "view_center_pick": "CURSOR",
    "view_center_lock": "LOCKED",
    "view_center_camera": "CAMERA_DATA",
    "view_lock_to_active": "LOCKED",
    "view_lock_clear": "UNLOCKED",
    "walk": "VIEW_CAMERA",
    "fly": "VIEW3D",
    "navigate": "VIEW3D",
    "dolly": "VIEWZOOM",
    "cursor3d": "CURSOR",
    "copybuffer": "COPYDOWN",
    "pastebuffer": "PASTEDOWN",
    "snap_cursor_to_active": "CURSOR",
    "snap_cursor_to_center": "CURSOR",
    "snap_cursor_to_grid": "CURSOR",
    "snap_cursor_to_selected": "CURSOR",
    "snap_selected_to_cursor": "CURSOR",
    "snap_selected_to_grid": "SNAP_GRID",
    "snap_selected_to_active": "CURSOR",
    "toggle_shading": "MATERIAL",
    "toggle_xray": "XRAY",
    "toggle_matcap_flip": "SHADING_RENDERED",
    "camera_to_view": "CAMERA_DATA",
    "camera_to_view_selected": "CAMERA_DATA",
    "object_as_camera": "CAMERA_DATA",
    "render_border": "RENDER_RESULT",
    "clear_render_border": "RENDER_RESULT",
    "clip_border": "ZOOM_SELECTED",
    "zoom_border": "ZOOM_SELECTED",
    "ruler_add": "TRACKING",
    "ruler_remove": "TRACKING",
    "object_mode_pie_or_toggle": "OBJECT_DATA",
    "transform_gizmo_set": "GIZMO",
    # Render
    "render": "RENDER_RESULT",
    "opengl": "RENDER_RESULT",
    "play_rendered_anim": "PLAY",
    "view_show": "RENDER_RESULT",
    "view_cancel": "CANCEL",
    # Marker
    "add": "ADD",
    "camera_bind": "CAMERA_DATA",
    "select_leftright": "ARROW_LEFTRIGHT",
    # WM misc
    "radial_control": "BRUSH_DATA",
    "toolbar": "TOOL_SETTINGS",
    "toolbar_fallback_pie": "TOOL_SETTINGS",
    "toolbar_prompt": "TOOL_SETTINGS",
    "quit_blender": "QUIT",
    "save_homefile": "FILE_TICK",
    "read_homefile": "FILE_FOLDER",
    "read_factory_settings": "LOOP_BACK",
    "revert_mainfile": "LOOP_BACK",
    "save_as_mainfile": "FILE_TICK",
    "save_userpref": "PREFERENCES",
    "save_homefile": "FILE_TICK",
    "search_operator": "VIEWZOOM",
    "drop_blend_file": "FILE_BLEND",
    "window_fullscreen_toggle": "FULLSCREEN_ENTER",
    "window_new": "WINDOW",
    "context_cycle_enum": "LOOP_BACK",
    "context_cycle_int": "LOOP_BACK",
    "context_set_boolean": "CHECKBOX_HLT",
    "context_set_enum": "COLLAPSEMENU",
    "context_set_float": "PROPERTIES",
    "context_set_int": "PROPERTIES",
    "context_toggle_enum": "CHECKBOX_HLT",
    "context_menu_enum": "COLLAPSEMENU",
    "context_pie_enum": "CURVE_NCIRCLE",
    "context_set_value": "PROPERTIES",
    "context_modal_mouse": "MOUSE_MOVE",
    "context_scale_float": "PROPERTIES",
    "context_scale_int": "PROPERTIES",
    "context_set_id": "PROPERTIES",
    "context_set_string": "FONT_DATA",
    "call_asset_shelf_popover": "ASSET_MANAGER",
    "operator_pie_enum": "CURVE_NCIRCLE",
    # Clip / tracking
    "view_pan": "ARROW_LEFTRIGHT",
    "view_zoom_ratio": "VIEWZOOM",
    "view_center_cursor": "CURSOR",
    "view_ndof": "ORIENTATION_GIMBAL",
    "track_markers": "TRACKING",
    "detect_features": "TRACKING",
    "solve_camera": "CAMERA_DATA",
    "clear_solution": "LOOP_BACK",
    "set_origin": "OBJECT_ORIGIN",
    "set_scale": "FULLSCREEN_ENTER",
    "set_axis": "ORIENTATION_GLOBAL",
    "bundles_to_mesh": "MESH_DATA",
    "track_to_empty": "EMPTY_DATA",
    "hide_tracks": "HIDE_ON",
    "hide_tracks_clear": "HIDE_OFF",
    "lock_tracks": "LOCKED",
    "lock_selection_toggle": "LOCKED",
    "add_marker": "ADD",
    "delete_marker": "TRASH",
    "delete_track": "TRASH",
    "rebuild_proxy": "FILE_REFRESH",
    "prefetch": "TEMP",
    "reload": "FILE_REFRESH",
    "mode_set": "COLLAPSEMENU",
    # Outliner
    "collection_new": "OUTLINER_COLLECTION",
    "collection_duplicate": "DUPLICATE",
    "collection_hierarchy_delete": "TRASH",
    "collection_instance": "OUTLINER_OB_EMPTY",
    "collection_isolate": "RESTRICT_VIEW_OFF",
    "collection_hide_inside": "HIDE_ON",
    "collection_show": "HIDE_OFF",
    "collection_show_inside": "HIDE_OFF",
    "collection_objects_select": "RESTRICT_SELECT_OFF",
    "collection_objects_deselect": "RESTRICT_SELECT_ON",
    "show_active": "ZOOM_SELECTED",
    "show_hierarchy": "OUTLINER",
    "show_one_level": "TRIA_DOWN",
    "id_delete": "TRASH",
    "id_remap": "LINKED",
    "item_activate": "MOUSE_LMB",
    "item_openclose": "TRIA_RIGHT",
    "object_operation": "OBJECT_DATA",
    "orphans_purge": "TRASH",
    "orphans_manage": "TRASH",
    "lib_relocate": "FILE_FOLDER",
    # Image
    "flip": "ARROW_LEFTRIGHT",
    "invert": "IMAGE_ALPHA",
    "rotate_orthogonal": "FILE_REFRESH",
    "save": "FILE_TICK",
    "save_as": "FILE_TICK",
    "save_all_modified": "FILE_TICK",
    "pack": "PACKAGE",
    "unpack": "PACKAGE",
    "new": "FILE_NEW",
    "open": "FILE_FOLDER",
    "replace": "FILE_REFRESH",
    "reload": "FILE_REFRESH",
    "view_zoom_border": "ZOOM_SELECTED",
    "render_border": "RENDER_RESULT",
    "clear_render_border": "RENDER_RESULT",
    "sample": "EYEDROPPER",
    "sample_line": "EYEDROPPER",
    "read_viewlayers": "RENDERLAYERS",
    "cycle_render_slot": "LOOP_BACK",
    # NLA
    "tweakmode_enter": "NLA_PUSHDOWN",
    "tweakmode_exit": "NLA_PUSHDOWN",
    "action_pushdown": "NLA_PUSHDOWN",
    "action_unlink": "UNLINKED",
    "actionclip_add": "ACTION",
    "transition_add": "IPO_BEZIER",
    "soundclip_add": "FILE_SOUND",
    "meta_add": "NLA_PUSHDOWN",
    "meta_remove": "NLA_PUSHDOWN",
    "apply_scale": "FULLSCREEN_ENTER",
    "clear_scale": "LOOP_BACK",
    "bake": "RENDER_ANIMATION",
    "move_up": "TRIA_UP",
    "move_down": "TRIA_DOWN",
    "mute_toggle": "MUTE_IPO_ON",
    "tracks_add": "ADD",
    "tracks_delete": "TRASH",
    "make_single_user": "UNLINKED",
    "swap": "ARROW_LEFTRIGHT",
    "selected_objects_add": "ADD",
    "snap": "SNAP_ON",
    "select_leftright": "ARROW_LEFTRIGHT",
    "duplicate_linked_move": "DUPLICATE",
    "action_sync_length": "PREVIEW_RANGE",
})

# Full-id overrides for remaining specific cases
FULL_ID_ICONS.update({
    "screen.animation_play": "PLAY",
    "view3d.move": "VIEW_PAN",
    "view3d.rotate": "FILE_REFRESH",
    "view3d.zoom": "VIEWZOOM",
    "view3d.view_pan": "ARROW_LEFTRIGHT",
    "view3d.fly": "VIEW3D",
    "view3d.walk": "VIEW3D",
    "view3d.navigate": "VIEW3D",
    "view3d.ndof_all": "ORIENTATION_GIMBAL",
    "view3d.ndof_orbit": "ORIENTATION_GIMBAL",
    "view3d.ndof_orbit_zoom": "ORIENTATION_GIMBAL",
    "view3d.ndof_pan": "ORIENTATION_GIMBAL",
    "view3d.dolly": "VIEWZOOM",
    "view3d.edit_mesh_extrude_individual_move": "NORMALS_VERTEX",
    "view3d.edit_mesh_extrude_manifold_normal": "NORMALS_FACE",
    "view3d.edit_mesh_extrude_move_shrink_fatten": "NORMALS_FACE",
    "view3d.bone_select_menu": "BONE_DATA",
    "view3d.select_menu": "RESTRICT_SELECT_OFF",
    "wm.radial_control": "BRUSH_DATA",
    "render.render": "RENDER_RESULT",
    "render.opengl": "RENDER_RESULT",
    "render.play_rendered_anim": "PLAY",
    "anim.change_frame": "TIME",
    "clip.view_pan": "ARROW_LEFTRIGHT",
    "image.view_pan": "ARROW_LEFTRIGHT",
    "image.view_zoom": "VIEWZOOM",
    "image.view_zoom_in": "ZOOM_IN",
    "image.view_zoom_out": "ZOOM_OUT",
    "image.view_zoom_border": "ZOOM_SELECTED",
})

FULL_ID_ICONS.update({
    "anim.replace_action": "ACTION",
    "graph.blend_offset": "IPO_BEZIER",
    "graph.blend_to_default": "IPO_BEZIER",
    "graph.blend_to_ease": "IPO_EASE_IN_OUT",
    "graph.butterworth_smooth": "MOD_SMOOTH",
    "graph.clean": "TRASH",
    "graph.driver_delete_invalid": "DRIVER",
    "graph.ease": "IPO_EASE_IN_OUT",
    "graph.easing_type": "IPO_EASE_IN_OUT",
    "graph.equalize_handles": "CURVE_BEZCURVE",
    "graph.euler_filter": "IPO_BEZIER",
    "graph.extrapolation_type": "IPO_CONSTANT",
    "graph.fmodifier_add": "MODIFIER",
    "graph.gaussian_smooth": "MOD_SMOOTH",
    "graph.ghost_curves_clear": "GHOST_DISABLED",
    "graph.ghost_curves_create": "GHOST_ENABLED",
    "graph.handle_type": "CURVE_BEZCURVE",
    "graph.interpolation_type": "IPO_BEZIER",
    "graph.keys_to_samples": "PARTICLE_POINT",
    "graph.match_slope": "IPO_BEZIER",
    "graph.samples_to_keys": "KEYFRAME_HLT",
    "graph.scale_average": "FULLSCREEN_ENTER",
    "graph.scale_from_neighbor": "FULLSCREEN_ENTER",
    "graph.sound_to_samples": "FILE_SOUND",
    "graph.time_offset": "TIME",
})

# Unmapped-operator sweep (v3.276): solid icon matches for factory-bound ops
# that previously fell back to DOT. Version-invalid names degrade via
# _icon_or_fallback, so newer icon names are safe to use here.
FULL_ID_ICONS.update({
    # Screen / areas / app
    "screen.redo_last": "OPTIONS",
    "screen.animation_step": "FRAME_NEXT",
    "screen.animation_cancel": "CANCEL",
    "screen.frame_offset": "FRAME_NEXT",
    "screen.time_jump": "TIME",
    "screen.screen_full_area": "FULLSCREEN_ENTER",
    "screen.area_join": "AREA_JOIN",
    "screen.area_swap": "AREA_SWAP",
    "screen.area_dupli": "DUPLICATE",
    "screen.area_move": "ARROW_LEFTRIGHT",
    "screen.workspace_cycle": "WORKSPACE",
    "screen.userpref_show": "PREFERENCES",
    "screen.region_context_menu": "KEY_MENU",
    "wm.doc_view_manual_ui_context": "HELP",
    "gizmogroup.gizmo_tweak": "GIZMO",
    # UI buttons
    "ui.copy_data_path_button": "COPYDOWN",
    "ui.reset_default_button": "LOOP_BACK",
    # File browser
    "file.directory_new": "NEWFOLDER",
    "file.bookmark_add": "BOOKMARKS",
    "file.refresh": "FILE_REFRESH",
    "file.parent": "FILE_PARENT",
    "file.next": "FORWARD",
    "file.previous": "BACK",
    "file.cancel": "CANCEL",
    # Console / text / info
    "console.execute": "CONSOLE",
    "text.run_script": "PLAY",
    "info.report_copy": "COPYDOWN",
    "info.report_delete": "TRASH",
    "info.report_replay": "PLAY",
    # Transform variants
    "transform.bend": "MOD_SIMPLEDEFORM",
    "transform.shear": "MOD_LATTICE",
    "transform.transform": "EMPTY_ARROWS",
    # 3D view
    "view3d.view_persportho": "VIEW_PERSPECTIVE",
    "view3d.interactive_add": "MESH_CUBE",
    "view2d.zoom_border": "ZOOM_SELECTED",
    "image.view_zoom_border": "ZOOM_SELECTED",
    "image.view_cursor_center": "PIVOT_CURSOR",
    # Object
    "object.voxel_remesh": "MOD_REMESH",
    "object.voxel_size_edit": "MOD_REMESH",
    "object.subdivision_set": "MOD_SUBSURF",
    "object.add_modifier_menu": "MODIFIER",
    "object.modifier_set_active": "MODIFIER",
    "object.metaball_add": "OUTLINER_OB_META",
    "object.hide_collection": "OUTLINER_COLLECTION",
    "object.transfer_mode": "OBJECT_DATAMODE",
    "object.vertex_group_remove_from": "GROUP_VERTEX",
    "mball.delete_metaelems": "TRASH",
    # Collections
    "collection.create": "COLLECTION_NEW",
    "collection.objects_add_active": "OUTLINER_COLLECTION",
    "collection.objects_remove": "OUTLINER_COLLECTION",
    "collection.objects_remove_active": "OUTLINER_COLLECTION",
    "collection.objects_remove_all": "OUTLINER_COLLECTION",
    # Constraints / pose
    "constraint.apply": "CONSTRAINT",
    "pose.constraint_add_with_targets": "CONSTRAINT",
    # Nodes
    "node.clipboard_copy": "COPYDOWN",
    "node.clipboard_paste": "PASTEDOWN",
    "node.delete_reconnect": "TRASH",
    "node.duplicate_move_keep_inputs": "DUPLICATE",
    "node.link": "LINKED",
    "node.join_nodes": "NODETREE",
    "node.join_named": "NODETREE",
    "node.group_separate": "NODETREE",
    "node.backimage_fit": "IMAGE_BACKGROUND",
    "node.backimage_move": "IMAGE_BACKGROUND",
    "node.backimage_zoom": "IMAGE_BACKGROUND",
    "node.backimage_sample": "IMAGE_BACKGROUND",
    # Grease pencil / annotation
    "gpencil.annotate": "GREASEPENCIL",
    "grease_pencil.sculpt_paint": "SCULPTMODE_HLT",
    "grease_pencil.vertex_brush_stroke": "VPAINT_HLT",
    "grease_pencil.weight_brush_stroke": "WPAINT_HLT",
    "grease_pencil.erase_box": "BRUSH_DATA",
    "grease_pencil.erase_lasso": "BRUSH_DATA",
    "grease_pencil.cyclical_set": "CURVE_BEZCIRCLE",
    # Paint / sculpt gestures
    "paint.hide_show_lasso_gesture": "HIDE_ON",
    "paint.hide_show_line_gesture": "HIDE_ON",
    "paint.hide_show_polyline_gesture": "HIDE_ON",
    "paint.visibility_filter": "HIDE_OFF",
    "paint.mask_line_gesture": "MOD_MASK",
    "paint.mask_polyline_gesture": "MOD_MASK",
    "paint.weight_gradient": "WPAINT_HLT",
    "sculpt.trim_line_gesture": "MOD_BOOLEAN",
    "sculpt.trim_polyline_gesture": "MOD_BOOLEAN",
    "sculpt.face_set_box_gesture": "FACESEL",
    "sculpt.face_set_lasso_gesture": "FACESEL",
    "sculpt.face_set_line_gesture": "FACESEL",
    "sculpt.face_set_polyline_gesture": "FACESEL",
    "brush.asset_activate": "BRUSHES_ALL",
    # Outliner
    "outliner.expanded_toggle": "OUTLINER",
    "outliner.id_copy": "COPYDOWN",
    "outliner.id_paste": "PASTEDOWN",
    "outliner.collection_exclude_set": "CHECKBOX_DEHLT",
    "outliner.collection_exclude_clear": "CHECKBOX_HLT",
    "outliner.drivers_add_selected": "DRIVER",
    "outliner.drivers_delete_selected": "DRIVER",
    "outliner.keyingset_add_selected": "KEYINGSET",
    "outliner.keyingset_remove_selected": "KEYINGSET",
    # Animation editors
    "action.bake_keys": "KEYFRAME",
    "graph.bake_keys": "KEYFRAME",
    "graph.click_insert": "KEYFRAME",
    "action.easing_type": "IPO_EASE_IN_OUT",
    "action.interpolation_type": "IPO_BEZIER",
    "action.handle_type": "HANDLE_ALIGNED",
    "action.keyframe_type": "KEYFRAME_HLT",
    "action.extrapolation_type": "IPO_CONSTANT",
    "nla.fmodifier_add": "MODIFIER",
    # Clip / mask
    "clip.copy_tracks": "COPYDOWN",
    "clip.paste_tracks": "PASTEDOWN",
    "mask.copy_splines": "COPYDOWN",
    "mask.paste_splines": "PASTEDOWN",
    "mask.primitive_square_add": "MESH_PLANE",
    "mask.shape_key_insert": "SHAPEKEY_DATA",
    # Font / curve
    "font.text_copy": "COPYDOWN",
    "font.text_cut": "COPYDOWN",
    "font.text_paste": "PASTEDOWN",
    "font.style_toggle": "BOLD",
    "curve.vertex_add": "VERTEXSEL",
    # Assets
    "asset.library_refresh": "FILE_REFRESH",
    "asset.catalog_undo": "LOOP_BACK",
    "asset.catalog_redo": "LOOP_FORWARDS",
})

# Second unmapped sweep (v3.277): name-obvious matches, incl. Jarand's picks.
FULL_ID_ICONS.update({
    # View navigation
    "view2d.ndof": "VIEW_PAN",
    "view2d.scroller_activate": "MOUSE_MMB_SCROLL",
    "view3d.xray_toggle": "XRAY",
    "view3d.toggle_xray": "XRAY",
    "view3d.wireframe_toggle": "MOD_WIREFRAME",
    # Text editor
    "text.cut": "COPYDOWN",
    "text.duplicate_line": "DUPLICATE",
    "text.line_number": "LINENUMBERS_ON",
    "text.comment_toggle": "SYNTAX_ON",
    # Console
    "console.copy_as_script": "COPYDOWN",
    # File browser
    "file.execute": "FILE_TICK",
    "file.mouse_execute": "FILE_TICK",
    "file.edit_directory_path": "FILE_FOLDER",
    "file.sort_column_ui_context": "SORTALPHA",
    # Context menus
    "buttons.context_menu": "KEY_MENU",
    "outliner.operation": "KEY_MENU",
    "screen.area_options": "KEY_MENU",
    # Areas / regions
    "screen.area_split": "AREA_JOIN",
    "screen.region_scale": "ARROW_LEFTRIGHT",
    "screen.region_quadview": "MESH_GRID",
    # Object / pose
    "object.shaderfx_copy": "SHADERFX",
    "object.shaderfx_remove": "SHADERFX",
    "object.vertex_parent_set": "CON_CHILDOF",
    "object.transform_axis_target": "CON_TRACKTO",
    "pose.select_parent": "CON_CHILDOF",
    # Mesh polybuild / extrude variants
    "mesh.polybuild_delete_at_cursor": "MOD_BUILD",
    "mesh.polybuild_extrude_at_cursor_move": "MOD_BUILD",
    "mesh.polybuild_face_at_cursor_move": "MOD_BUILD",
    # Nodes
    "node.move_detach_links": "UNLINKED",
    "node.move_detach_links_release": "UNLINKED",
    "node.render_changed": "RENDER_STILL",
    # Sequencer
    "sequencer.preview_duplicate_move": "SEQ_STRIP_DUPLICATE",
    "sequencer.preview_duplicate_move_linked": "SEQ_STRIP_DUPLICATE",
    "sequencer.split_multicam": "SEQ_SPLITVIEW",
    "sequencer.retiming_key_delete": "TIME",
    "sequencer.retiming_segment_speed_set": "MOD_TIME",
    "sequencer.select_handle": "RESTRICT_SELECT_OFF",
    "sequencer.select_side_of_frame": "RESTRICT_SELECT_OFF",
    # Spreadsheet
    "spreadsheet.fit_column": "SPREADSHEET",
    "spreadsheet.resize_column": "SPREADSHEET",
    "spreadsheet.reorder_columns": "SPREADSHEET",
    # Sculpt / paint
    "sculpt.uv_sculpt_grab": "BRUSHES_ALL",
    "sculpt.uv_sculpt_pinch": "BRUSHES_ALL",
    "sculpt.uv_sculpt_relax": "BRUSHES_ALL",
    "sculpt.project_line_gesture": "MOD_SHRINKWRAP",
    # Motion tracking
    "clip.slide_marker": "MARKER",
    "clip.add_marker_slide": "MARKER",
    "clip.slide_plane_marker": "MARKER",
    "clip.disable_markers": "MARKER",
    "clip.graph_disable_markers": "MARKER",
    "clip.clear_track_path": "TRACKING_CLEAR_FORWARDS",
    "clip.join_tracks": "TRACKING",
    "clip.graph_delete_curve": "FCURVE",
    "clip.graph_delete_knot": "FCURVE",
    "clip.graph_select": "RESTRICT_SELECT_OFF",
    "clip.graph_select_box": "RESTRICT_SELECT_OFF",
    "clip.graph_center_current_frame": "TIME",
    # Mask
    "mask.slide_point": "MOD_MASK",
    "mask.add_vertex_slide": "MOD_MASK",
    "mask.add_feather_vertex_slide": "MOD_MASK",
    "mask.slide_spline_curvature": "MOD_MASK",
    # Paint curve
    "paintcurve.add_point_slide": "CURVE_BEZCURVE",
    "paintcurve.slide": "CURVE_BEZCURVE",
    "paintcurve.select": "CURVE_BEZCURVE",
    "paintcurve.cursor": "PIVOT_CURSOR",
    "paintcurve.delete_point": "TRASH",
    # Grease pencil
    "grease_pencil.join_selection": "AUTOMERGE_ON",
    # Fonts
    "font.change_character": "FONT_DATA",
    "font.change_spacing": "FONT_DATA",
    # UI views
    "ui.view_item_delete": "TRASH",
    "ui.view_item_select": "RESTRICT_SELECT_OFF",
    # Image
    "image.curves_point_set": "FCURVE",
})
